/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.ActionsApi
import app.spatio.client.models.ActionDescriptor
import app.spatio.client.models.ApiError
import app.spatio.client.models.CoreAction
import app.spatio.client.models.CoreActionListResponse
import app.spatio.client.models.ExecuteActionRequest
import app.spatio.client.models.ExecuteActionResponse

class ActionsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ActionsApi
        //val apiInstance = ActionsApi()

        // to test executeAction
        should("test executeAction") {
            // uncomment below to test executeAction
            //val executeActionRequest : ExecuteActionRequest =  // ExecuteActionRequest | 
            //val result : ExecuteActionResponse = apiInstance.executeAction(executeActionRequest)
            //result shouldBe ("TODO")
        }

        // to test getCoreAction
        should("test getCoreAction") {
            // uncomment below to test getCoreAction
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : CoreAction = apiInstance.getCoreAction(id)
            //result shouldBe ("TODO")
        }

        // to test listAvailableActions
        should("test listAvailableActions") {
            // uncomment below to test listAvailableActions
            //val result : kotlin.collections.List<ActionDescriptor> = apiInstance.listAvailableActions()
            //result shouldBe ("TODO")
        }

        // to test listCoreActions
        should("test listCoreActions") {
            // uncomment below to test listCoreActions
            //val result : CoreActionListResponse = apiInstance.listCoreActions()
            //result shouldBe ("TODO")
        }

        // to test listCoreActionsByPlatform
        should("test listCoreActionsByPlatform") {
            // uncomment below to test listCoreActionsByPlatform
            //val platform : kotlin.String = platform_example // kotlin.String | 
            //val result : CoreActionListResponse = apiInstance.listCoreActionsByPlatform(platform)
            //result shouldBe ("TODO")
        }

        // to test listPlatformActions
        should("test listPlatformActions") {
            // uncomment below to test listPlatformActions
            //val platform : kotlin.String = platform_example // kotlin.String | 
            //val result : kotlin.collections.List<ActionDescriptor> = apiInstance.listPlatformActions(platform)
            //result shouldBe ("TODO")
        }

    }
}
