/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.AgentsApi
import app.spatio.client.models.Agent
import app.spatio.client.models.AgentConversation
import app.spatio.client.models.AgentConversationListResponse
import app.spatio.client.models.AgentListResponse
import app.spatio.client.models.AgentMessage
import app.spatio.client.models.AgentMessageListResponse
import app.spatio.client.models.AgentSessionContext
import app.spatio.client.models.ApiError
import app.spatio.client.models.CreateAgentConversationRequest
import app.spatio.client.models.CreateAgentMessageRequest
import app.spatio.client.models.CreateAgentRequest
import app.spatio.client.models.ExecuteActionRequest
import app.spatio.client.models.ExecuteActionResponse
import app.spatio.client.models.PreconfiguredAgent
import app.spatio.client.models.UpdateAgentRequest

class AgentsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AgentsApi
        //val apiInstance = AgentsApi()

        // to test createAgent
        should("test createAgent") {
            // uncomment below to test createAgent
            //val createAgentRequest : CreateAgentRequest =  // CreateAgentRequest | 
            //val result : Agent = apiInstance.createAgent(createAgentRequest)
            //result shouldBe ("TODO")
        }

        // to test createAgentConversation
        should("test createAgentConversation") {
            // uncomment below to test createAgentConversation
            //val createAgentConversationRequest : CreateAgentConversationRequest =  // CreateAgentConversationRequest | 
            //val result : AgentConversation = apiInstance.createAgentConversation(createAgentConversationRequest)
            //result shouldBe ("TODO")
        }

        // to test createAgentMessage
        should("test createAgentMessage") {
            // uncomment below to test createAgentMessage
            //val id : kotlin.String = id_example // kotlin.String | 
            //val createAgentMessageRequest : CreateAgentMessageRequest =  // CreateAgentMessageRequest | 
            //val result : AgentMessage = apiInstance.createAgentMessage(id, createAgentMessageRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteAgent
        should("test deleteAgent") {
            // uncomment below to test deleteAgent
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.deleteAgent(id)
        }

        // to test executeAgentAction
        should("test executeAgentAction") {
            // uncomment below to test executeAgentAction
            //val executeActionRequest : ExecuteActionRequest =  // ExecuteActionRequest | 
            //val result : ExecuteActionResponse = apiInstance.executeAgentAction(executeActionRequest)
            //result shouldBe ("TODO")
        }

        // to test getAgent
        should("test getAgent") {
            // uncomment below to test getAgent
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : Agent = apiInstance.getAgent(id)
            //result shouldBe ("TODO")
        }

        // to test getAgentConversation
        should("test getAgentConversation") {
            // uncomment below to test getAgentConversation
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : AgentConversation = apiInstance.getAgentConversation(id)
            //result shouldBe ("TODO")
        }

        // to test getAgentSessionContext
        should("test getAgentSessionContext") {
            // uncomment below to test getAgentSessionContext
            //val result : AgentSessionContext = apiInstance.getAgentSessionContext()
            //result shouldBe ("TODO")
        }

        // to test listAgentConversationMessages
        should("test listAgentConversationMessages") {
            // uncomment below to test listAgentConversationMessages
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : AgentMessageListResponse = apiInstance.listAgentConversationMessages(id)
            //result shouldBe ("TODO")
        }

        // to test listAgentConversations
        should("test listAgentConversations") {
            // uncomment below to test listAgentConversations
            //val result : AgentConversationListResponse = apiInstance.listAgentConversations()
            //result shouldBe ("TODO")
        }

        // to test listAgents
        should("test listAgents") {
            // uncomment below to test listAgents
            //val result : AgentListResponse = apiInstance.listAgents()
            //result shouldBe ("TODO")
        }

        // to test listPreconfiguredAgents
        should("test listPreconfiguredAgents") {
            // uncomment below to test listPreconfiguredAgents
            //val result : kotlin.collections.List<PreconfiguredAgent> = apiInstance.listPreconfiguredAgents()
            //result shouldBe ("TODO")
        }

        // to test updateAgent
        should("test updateAgent") {
            // uncomment below to test updateAgent
            //val id : kotlin.String = id_example // kotlin.String | 
            //val updateAgentRequest : UpdateAgentRequest =  // UpdateAgentRequest | 
            //val result : Agent = apiInstance.updateAgent(id, updateAgentRequest)
            //result shouldBe ("TODO")
        }

    }
}
