/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.AppsApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.App
import app.spatio.client.models.AppFileContentResponse
import app.spatio.client.models.AppFileListResponse
import app.spatio.client.models.AppListResponse
import app.spatio.client.models.CreateAppRequest
import app.spatio.client.models.UpdateAppRequest
import app.spatio.client.models.WriteAppFileRequest

class AppsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AppsApi
        //val apiInstance = AppsApi()

        // to test createApp
        should("test createApp") {
            // uncomment below to test createApp
            //val createAppRequest : CreateAppRequest =  // CreateAppRequest | 
            //val result : App = apiInstance.createApp(createAppRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteApp
        should("test deleteApp") {
            // uncomment below to test deleteApp
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.deleteApp(id)
        }

        // to test deleteAppFile
        should("test deleteAppFile") {
            // uncomment below to test deleteAppFile
            //val id : kotlin.String = id_example // kotlin.String | 
            //val path : kotlin.String = path_example // kotlin.String | 
            //apiInstance.deleteAppFile(id, path)
        }

        // to test getApp
        should("test getApp") {
            // uncomment below to test getApp
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : App = apiInstance.getApp(id)
            //result shouldBe ("TODO")
        }

        // to test listAppFiles
        should("test listAppFiles") {
            // uncomment below to test listAppFiles
            //val id : kotlin.String = id_example // kotlin.String | 
            //val path : kotlin.String = path_example // kotlin.String | 
            //val result : AppFileListResponse = apiInstance.listAppFiles(id, path)
            //result shouldBe ("TODO")
        }

        // to test listApps
        should("test listApps") {
            // uncomment below to test listApps
            //val result : AppListResponse = apiInstance.listApps()
            //result shouldBe ("TODO")
        }

        // to test readAppFile
        should("test readAppFile") {
            // uncomment below to test readAppFile
            //val id : kotlin.String = id_example // kotlin.String | 
            //val path : kotlin.String = path_example // kotlin.String | 
            //val result : AppFileContentResponse = apiInstance.readAppFile(id, path)
            //result shouldBe ("TODO")
        }

        // to test updateApp
        should("test updateApp") {
            // uncomment below to test updateApp
            //val id : kotlin.String = id_example // kotlin.String | 
            //val updateAppRequest : UpdateAppRequest =  // UpdateAppRequest | 
            //val result : App = apiInstance.updateApp(id, updateAppRequest)
            //result shouldBe ("TODO")
        }

        // to test workspaceCreateApp
        should("test workspaceCreateApp") {
            // uncomment below to test workspaceCreateApp
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceCreateApp(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceDeleteApp
        should("test workspaceDeleteApp") {
            // uncomment below to test workspaceDeleteApp
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceDeleteApp(org, workspace, id)
        }

        // to test workspaceGetApp
        should("test workspaceGetApp") {
            // uncomment below to test workspaceGetApp
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetApp(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceListApps
        should("test workspaceListApps") {
            // uncomment below to test workspaceListApps
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListApps(org, workspace)
            //result shouldBe ("TODO")
        }

        // to test workspaceUpdateApp
        should("test workspaceUpdateApp") {
            // uncomment below to test workspaceUpdateApp
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdateApp(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test writeAppFile
        should("test writeAppFile") {
            // uncomment below to test writeAppFile
            //val id : kotlin.String = id_example // kotlin.String | 
            //val writeAppFileRequest : WriteAppFileRequest =  // WriteAppFileRequest | 
            //apiInstance.writeAppFile(id, writeAppFileRequest)
        }

    }
}
