/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.FoldersApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.CreateEmailFolderRequest
import app.spatio.client.models.EmailFolder
import app.spatio.client.models.EmailFolderListResponse
import app.spatio.client.models.MoveEmailsRequest
import app.spatio.client.models.UpdateEmailFolderRequest

class FoldersApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FoldersApi
        //val apiInstance = FoldersApi()

        // to test createEmailFolder
        should("test createEmailFolder") {
            // uncomment below to test createEmailFolder
            //val createEmailFolderRequest : CreateEmailFolderRequest =  // CreateEmailFolderRequest | 
            //val result : EmailFolder = apiInstance.createEmailFolder(createEmailFolderRequest)
            //result shouldBe ("TODO")
        }

        // to test deleteEmailFolder
        should("test deleteEmailFolder") {
            // uncomment below to test deleteEmailFolder
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.deleteEmailFolder(id)
        }

        // to test listEmailFolders
        should("test listEmailFolders") {
            // uncomment below to test listEmailFolders
            //val result : EmailFolderListResponse = apiInstance.listEmailFolders()
            //result shouldBe ("TODO")
        }

        // to test listFolderEmails
        should("test listFolderEmails") {
            // uncomment below to test listFolderEmails
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.listFolderEmails(id)
            //result shouldBe ("TODO")
        }

        // to test moveEmailsToFolder
        should("test moveEmailsToFolder") {
            // uncomment below to test moveEmailsToFolder
            //val id : kotlin.String = id_example // kotlin.String | 
            //val moveEmailsRequest : MoveEmailsRequest =  // MoveEmailsRequest | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.moveEmailsToFolder(id, moveEmailsRequest)
            //result shouldBe ("TODO")
        }

        // to test updateEmailFolder
        should("test updateEmailFolder") {
            // uncomment below to test updateEmailFolder
            //val id : kotlin.String = id_example // kotlin.String | 
            //val updateEmailFolderRequest : UpdateEmailFolderRequest =  // UpdateEmailFolderRequest | 
            //val result : EmailFolder = apiInstance.updateEmailFolder(id, updateEmailFolderRequest)
            //result shouldBe ("TODO")
        }

    }
}
