/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.LogosApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.GetDomainLogo200Response

class LogosApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of LogosApi
        //val apiInstance = LogosApi()

        // to test getDomainLogo
        should("test getDomainLogo") {
            // uncomment below to test getDomainLogo
            //val domain : kotlin.String = domain_example // kotlin.String | 
            //val result : GetDomainLogo200Response = apiInstance.getDomainLogo(domain)
            //result shouldBe ("TODO")
        }

        // to test getEmailLogo
        should("test getEmailLogo") {
            // uncomment below to test getEmailLogo
            //val email : kotlin.String = email_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getEmailLogo(email)
            //result shouldBe ("TODO")
        }

        // to test getLogosBatch
        should("test getLogosBatch") {
            // uncomment below to test getLogosBatch
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getLogosBatch(requestBody)
            //result shouldBe ("TODO")
        }

    }
}
