/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.MailApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.BulkArchiveRequest
import app.spatio.client.models.BulkArchiveResponse
import app.spatio.client.models.BulkDeleteEmailsRequest
import app.spatio.client.models.BulkDeleteEmailsResponse
import app.spatio.client.models.BulkMarkReadRequest
import app.spatio.client.models.BulkMarkReadResponse
import app.spatio.client.models.CreateDraftRequest
import app.spatio.client.models.CreateLabelRequest
import app.spatio.client.models.CreateLabelResponse
import app.spatio.client.models.CreateNote400Response
import app.spatio.client.models.DraftResponse
import app.spatio.client.models.GetEmailResponse
import app.spatio.client.models.GetThreadResponse
import app.spatio.client.models.ListDraftsResponse
import app.spatio.client.models.ListEmailsResponse
import app.spatio.client.models.ListLabelsResponse
import app.spatio.client.models.ReplyEmailRequest
import app.spatio.client.models.SearchEmailsResponse
import app.spatio.client.models.SendEmailRequest
import app.spatio.client.models.SendEmailResponse
import app.spatio.client.models.SuccessFlag
import app.spatio.client.models.UpdateDraftRequest
import app.spatio.client.models.UpdateEmailRequest
import app.spatio.client.models.UpdateEmailResponse

class MailApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MailApi
        //val apiInstance = MailApi()

        // to test bulkArchiveEmails
        should("test bulkArchiveEmails") {
            // uncomment below to test bulkArchiveEmails
            //val bulkArchiveRequest : BulkArchiveRequest =  // BulkArchiveRequest | 
            //val result : BulkArchiveResponse = apiInstance.bulkArchiveEmails(bulkArchiveRequest)
            //result shouldBe ("TODO")
        }

        // to test bulkDeleteEmails
        should("test bulkDeleteEmails") {
            // uncomment below to test bulkDeleteEmails
            //val bulkDeleteEmailsRequest : BulkDeleteEmailsRequest =  // BulkDeleteEmailsRequest | 
            //val result : BulkDeleteEmailsResponse = apiInstance.bulkDeleteEmails(bulkDeleteEmailsRequest)
            //result shouldBe ("TODO")
        }

        // to test bulkMarkEmailsRead
        should("test bulkMarkEmailsRead") {
            // uncomment below to test bulkMarkEmailsRead
            //val bulkMarkReadRequest : BulkMarkReadRequest =  // BulkMarkReadRequest | 
            //val result : BulkMarkReadResponse = apiInstance.bulkMarkEmailsRead(bulkMarkReadRequest)
            //result shouldBe ("TODO")
        }

        // to test createDraft
        should("test createDraft") {
            // uncomment below to test createDraft
            //val createDraftRequest : CreateDraftRequest =  // CreateDraftRequest | 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : DraftResponse = apiInstance.createDraft(createDraftRequest, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test createEmailLabel
        should("test createEmailLabel") {
            // uncomment below to test createEmailLabel
            //val createLabelRequest : CreateLabelRequest =  // CreateLabelRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : CreateLabelResponse = apiInstance.createEmailLabel(createLabelRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test createMailTemplate
        should("test createMailTemplate") {
            // uncomment below to test createMailTemplate
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.createMailTemplate(requestBody)
            //result shouldBe ("TODO")
        }

        // to test deleteDraft
        should("test deleteDraft") {
            // uncomment below to test deleteDraft
            //val id : kotlin.String = id_example // kotlin.String | Draft id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //apiInstance.deleteDraft(id, accountId, xWorkspaceID)
        }

        // to test deleteEmail
        should("test deleteEmail") {
            // uncomment below to test deleteEmail
            //val id : kotlin.String = id_example // kotlin.String | Email message id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SuccessFlag = apiInstance.deleteEmail(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test deleteEmailLabel
        should("test deleteEmailLabel") {
            // uncomment below to test deleteEmailLabel
            //val id : kotlin.String = id_example // kotlin.String | Label id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //apiInstance.deleteEmailLabel(id, accountId, xWorkspaceID)
        }

        // to test deleteMailTemplate
        should("test deleteMailTemplate") {
            // uncomment below to test deleteMailTemplate
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.deleteMailTemplate(id)
        }

        // to test getEmail
        should("test getEmail") {
            // uncomment below to test getEmail
            //val id : kotlin.String = id_example // kotlin.String | Email message id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : GetEmailResponse = apiInstance.getEmail(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getEmailAttachment
        should("test getEmailAttachment") {
            // uncomment below to test getEmailAttachment
            //val messageId : kotlin.String = messageId_example // kotlin.String | Message id the attachment belongs to.
            //val attachmentId : kotlin.String = attachmentId_example // kotlin.String | Attachment id within the message.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : java.io.File = apiInstance.getEmailAttachment(messageId, attachmentId, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getEmailThread
        should("test getEmailThread") {
            // uncomment below to test getEmailThread
            //val id : kotlin.String = id_example // kotlin.String | Thread id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : GetThreadResponse = apiInstance.getEmailThread(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getMailTemplate
        should("test getMailTemplate") {
            // uncomment below to test getMailTemplate
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getMailTemplate(id)
            //result shouldBe ("TODO")
        }

        // to test getMailThreadTracking
        should("test getMailThreadTracking") {
            // uncomment below to test getMailThreadTracking
            //val threadId : kotlin.String = threadId_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getMailThreadTracking(threadId)
            //result shouldBe ("TODO")
        }

        // to test instantiateMailTemplate
        should("test instantiateMailTemplate") {
            // uncomment below to test instantiateMailTemplate
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.instantiateMailTemplate(id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test listDrafts
        should("test listDrafts") {
            // uncomment below to test listDrafts
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Restrict to these connected-account row ids. Mutually orthogonal to `providers` — when both are set the intersection is used. 
            //val providers : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Restrict to these provider ids (`gmail`, `outlook`).
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val nextPageToken : kotlin.String = nextPageToken_example // kotlin.String | 
            //val result : ListDraftsResponse = apiInstance.listDrafts(xWorkspaceID, accountIds, providers, limit, nextPageToken)
            //result shouldBe ("TODO")
        }

        // to test listEmailLabels
        should("test listEmailLabels") {
            // uncomment below to test listEmailLabels
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : ListLabelsResponse = apiInstance.listEmailLabels(accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test listEmails
        should("test listEmails") {
            // uncomment below to test listEmails
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Restrict to these connected-account row ids. Mutually orthogonal to `providers` — when both are set the intersection is used. 
            //val providers : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Restrict to these provider ids (`gmail`, `outlook`).
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val query : kotlin.String = query_example // kotlin.String | Provider-specific full-text query (e.g. Gmail search syntax).
            //val labels : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Filter to messages carrying every label.
            //val folder : kotlin.String = folder_example // kotlin.String | Logical folder filter. Canonical values: `inbox`, `sent`, `starred`, `trash`, `archive`. Provider-specific folders accepted as opaque strings. 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val result : ListEmailsResponse = apiInstance.listEmails(accountIds, providers, xWorkspaceID, query, labels, folder, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test listMailTemplates
        should("test listMailTemplates") {
            // uncomment below to test listMailTemplates
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.listMailTemplates()
            //result shouldBe ("TODO")
        }

        // to test replyEmail
        should("test replyEmail") {
            // uncomment below to test replyEmail
            //val messageId : kotlin.String = messageId_example // kotlin.String | Id of the message being replied to.
            //val replyEmailRequest : ReplyEmailRequest =  // ReplyEmailRequest | 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SendEmailResponse = apiInstance.replyEmail(messageId, replyEmailRequest, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test saveMailTemplate
        should("test saveMailTemplate") {
            // uncomment below to test saveMailTemplate
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.saveMailTemplate(requestBody)
            //result shouldBe ("TODO")
        }

        // to test searchEmails
        should("test searchEmails") {
            // uncomment below to test searchEmails
            //val q : kotlin.String = q_example // kotlin.String | Provider-specific full-text query string.
            //val accountIds : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Restrict to these connected-account row ids. Mutually orthogonal to `providers` — when both are set the intersection is used. 
            //val providers : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Restrict to these provider ids (`gmail`, `outlook`).
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val from : kotlin.String = from_example // kotlin.String | 
            //val to : kotlin.String = to_example // kotlin.String | 
            //val subject : kotlin.String = subject_example // kotlin.String | 
            //val hasAttachment : kotlin.Boolean = true // kotlin.Boolean | 
            //val isUnread : kotlin.Boolean = true // kotlin.Boolean | 
            //val isStarred : kotlin.Boolean = true // kotlin.Boolean | 
            //val labels : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | 
            //val after : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | Inclusive lower-bound date.
            //val before : java.time.OffsetDateTime = 2013-10-20T19:20:30+01:00 // java.time.OffsetDateTime | Inclusive upper-bound date.
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val nextPageToken : kotlin.String = nextPageToken_example // kotlin.String | Cursor returned by the previous call.
            //val result : SearchEmailsResponse = apiInstance.searchEmails(q, accountIds, providers, xWorkspaceID, from, to, subject, hasAttachment, isUnread, isStarred, labels, after, before, limit, nextPageToken)
            //result shouldBe ("TODO")
        }

        // to test sendDraft
        should("test sendDraft") {
            // uncomment below to test sendDraft
            //val id : kotlin.String = id_example // kotlin.String | Draft id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SendEmailResponse = apiInstance.sendDraft(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test sendEmail
        should("test sendEmail") {
            // uncomment below to test sendEmail
            //val sendEmailRequest : SendEmailRequest =  // SendEmailRequest | 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SendEmailResponse = apiInstance.sendEmail(sendEmailRequest, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test updateDraft
        should("test updateDraft") {
            // uncomment below to test updateDraft
            //val id : kotlin.String = id_example // kotlin.String | Draft id.
            //val updateDraftRequest : UpdateDraftRequest =  // UpdateDraftRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : DraftResponse = apiInstance.updateDraft(id, updateDraftRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test updateEmail
        should("test updateEmail") {
            // uncomment below to test updateEmail
            //val id : kotlin.String = id_example // kotlin.String | Email message id.
            //val updateEmailRequest : UpdateEmailRequest =  // UpdateEmailRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : UpdateEmailResponse = apiInstance.updateEmail(id, updateEmailRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test updateMailTemplate
        should("test updateMailTemplate") {
            // uncomment below to test updateMailTemplate
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.updateMailTemplate(id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceAddMailMessageLabels
        should("test workspaceAddMailMessageLabels") {
            // uncomment below to test workspaceAddMailMessageLabels
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val messageId : kotlin.String = messageId_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceAddMailMessageLabels(org, workspace, messageId, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceCreateMailDraft
        should("test workspaceCreateMailDraft") {
            // uncomment below to test workspaceCreateMailDraft
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceCreateMailDraft(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceCreateMailLabel
        should("test workspaceCreateMailLabel") {
            // uncomment below to test workspaceCreateMailLabel
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceCreateMailLabel(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceDeleteMail
        should("test workspaceDeleteMail") {
            // uncomment below to test workspaceDeleteMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceDeleteMail(org, workspace, id)
        }

        // to test workspaceDeleteMailDraft
        should("test workspaceDeleteMailDraft") {
            // uncomment below to test workspaceDeleteMailDraft
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceDeleteMailDraft(org, workspace, id)
        }

        // to test workspaceDeleteMailLabel
        should("test workspaceDeleteMailLabel") {
            // uncomment below to test workspaceDeleteMailLabel
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceDeleteMailLabel(org, workspace, id)
        }

        // to test workspaceGetMail
        should("test workspaceGetMail") {
            // uncomment below to test workspaceGetMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetMail(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceGetMailAttachment
        should("test workspaceGetMailAttachment") {
            // uncomment below to test workspaceGetMailAttachment
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val messageId : kotlin.String = messageId_example // kotlin.String | 
            //val attachmentId : kotlin.String = attachmentId_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetMailAttachment(org, workspace, messageId, attachmentId)
            //result shouldBe ("TODO")
        }

        // to test workspaceGetMailById
        should("test workspaceGetMailById") {
            // uncomment below to test workspaceGetMailById
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetMailById(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceGetMailDraft
        should("test workspaceGetMailDraft") {
            // uncomment below to test workspaceGetMailDraft
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetMailDraft(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceGetMailThread
        should("test workspaceGetMailThread") {
            // uncomment below to test workspaceGetMailThread
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetMailThread(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceListMail
        should("test workspaceListMail") {
            // uncomment below to test workspaceListMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListMail(org, workspace)
            //result shouldBe ("TODO")
        }

        // to test workspaceListMailDrafts
        should("test workspaceListMailDrafts") {
            // uncomment below to test workspaceListMailDrafts
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListMailDrafts(org, workspace)
            //result shouldBe ("TODO")
        }

        // to test workspaceListMailLabels
        should("test workspaceListMailLabels") {
            // uncomment below to test workspaceListMailLabels
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListMailLabels(org, workspace)
            //result shouldBe ("TODO")
        }

        // to test workspacePatchMail
        should("test workspacePatchMail") {
            // uncomment below to test workspacePatchMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspacePatchMail(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceRemoveMailMessageLabel
        should("test workspaceRemoveMailMessageLabel") {
            // uncomment below to test workspaceRemoveMailMessageLabel
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val messageId : kotlin.String = messageId_example // kotlin.String | 
            //val labelId : kotlin.String = labelId_example // kotlin.String | 
            //apiInstance.workspaceRemoveMailMessageLabel(org, workspace, messageId, labelId)
        }

        // to test workspaceReplyMail
        should("test workspaceReplyMail") {
            // uncomment below to test workspaceReplyMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceReplyMail(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceSearchMail
        should("test workspaceSearchMail") {
            // uncomment below to test workspaceSearchMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val q : kotlin.String = q_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceSearchMail(org, workspace, q)
            //result shouldBe ("TODO")
        }

        // to test workspaceSendMail
        should("test workspaceSendMail") {
            // uncomment below to test workspaceSendMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceSendMail(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceSendMailDraft
        should("test workspaceSendMailDraft") {
            // uncomment below to test workspaceSendMailDraft
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceSendMailDraft(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceSendMailEmailAlias
        should("test workspaceSendMailEmailAlias") {
            // uncomment below to test workspaceSendMailEmailAlias
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceSendMailEmailAlias(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceUpdateMail
        should("test workspaceUpdateMail") {
            // uncomment below to test workspaceUpdateMail
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdateMail(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceUpdateMailDraft
        should("test workspaceUpdateMailDraft") {
            // uncomment below to test workspaceUpdateMailDraft
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdateMailDraft(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceUpdateMailLabel
        should("test workspaceUpdateMailLabel") {
            // uncomment below to test workspaceUpdateMailLabel
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdateMailLabel(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

    }
}
