/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.MiscApi
import app.spatio.client.models.ApiError

class MiscApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MiscApi
        //val apiInstance = MiscApi()

        // to test deletePinnedPlatform
        should("test deletePinnedPlatform") {
            // uncomment below to test deletePinnedPlatform
            //val platformId : kotlin.String = platformId_example // kotlin.String | 
            //apiInstance.deletePinnedPlatform(platformId)
        }

        // to test getBootstrap
        should("test getBootstrap") {
            // uncomment below to test getBootstrap
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getBootstrap()
            //result shouldBe ("TODO")
        }

        // to test getOnboardingInvitations
        should("test getOnboardingInvitations") {
            // uncomment below to test getOnboardingInvitations
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getOnboardingInvitations()
            //result shouldBe ("TODO")
        }

        // to test getPinnedPlatforms
        should("test getPinnedPlatforms") {
            // uncomment below to test getPinnedPlatforms
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getPinnedPlatforms()
            //result shouldBe ("TODO")
        }

        // to test getPlatformPreferences
        should("test getPlatformPreferences") {
            // uncomment below to test getPlatformPreferences
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getPlatformPreferences()
            //result shouldBe ("TODO")
        }

        // to test getPlatformSettingsLegacy
        should("test getPlatformSettingsLegacy") {
            // uncomment below to test getPlatformSettingsLegacy
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getPlatformSettingsLegacy()
            //result shouldBe ("TODO")
        }

        // to test getThreadsStatus
        should("test getThreadsStatus") {
            // uncomment below to test getThreadsStatus
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getThreadsStatus()
            //result shouldBe ("TODO")
        }

        // to test getUserPermissions
        should("test getUserPermissions") {
            // uncomment below to test getUserPermissions
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getUserPermissions()
            //result shouldBe ("TODO")
        }

        // to test getWorkspaceActivity
        should("test getWorkspaceActivity") {
            // uncomment below to test getWorkspaceActivity
            //val workspaceId : kotlin.String = workspaceId_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getWorkspaceActivity(workspaceId, limit)
            //result shouldBe ("TODO")
        }

        // to test getWorkspaceLayout
        should("test getWorkspaceLayout") {
            // uncomment below to test getWorkspaceLayout
            //val workspaceId : kotlin.String = workspaceId_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getWorkspaceLayout(workspaceId)
            //result shouldBe ("TODO")
        }

        // to test putPinnedPlatform
        should("test putPinnedPlatform") {
            // uncomment below to test putPinnedPlatform
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.putPinnedPlatform(requestBody)
        }

        // to test putPlatformPreferences
        should("test putPlatformPreferences") {
            // uncomment below to test putPlatformPreferences
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.putPlatformPreferences(requestBody)
        }

        // to test putWorkspaceLayout
        should("test putWorkspaceLayout") {
            // uncomment below to test putWorkspaceLayout
            //val workspaceId : kotlin.String = workspaceId_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.putWorkspaceLayout(workspaceId, requestBody)
        }

        // to test reorderPinnedPlatforms
        should("test reorderPinnedPlatforms") {
            // uncomment below to test reorderPinnedPlatforms
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //apiInstance.reorderPinnedPlatforms(requestBody)
        }

        // to test resetPlatformPreferences
        should("test resetPlatformPreferences") {
            // uncomment below to test resetPlatformPreferences
            //apiInstance.resetPlatformPreferences()
        }

        // to test updateUserProfile
        should("test updateUserProfile") {
            // uncomment below to test updateUserProfile
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.updateUserProfile(requestBody)
            //result shouldBe ("TODO")
        }

        // to test validateOrganizationSlug
        should("test validateOrganizationSlug") {
            // uncomment below to test validateOrganizationSlug
            //val slug : kotlin.String = slug_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.validateOrganizationSlug(slug)
            //result shouldBe ("TODO")
        }

        // to test validateWorkspaceSlug
        should("test validateWorkspaceSlug") {
            // uncomment below to test validateWorkspaceSlug
            //val slug : kotlin.String = slug_example // kotlin.String | 
            //val organizationId : kotlin.String = organizationId_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.validateWorkspaceSlug(slug, organizationId)
            //result shouldBe ("TODO")
        }

    }
}
