/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.NavigationApi
import app.spatio.client.models.ApiError

class NavigationApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NavigationApi
        //val apiInstance = NavigationApi()

        // to test getNavigation
        should("test getNavigation") {
            // uncomment below to test getNavigation
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getNavigation()
            //result shouldBe ("TODO")
        }

    }
}
