/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.NotesApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.Block
import app.spatio.client.models.BlockListResponse
import app.spatio.client.models.CommentListResponse
import app.spatio.client.models.CommentMutationResponse
import app.spatio.client.models.CommentResponse
import app.spatio.client.models.CreateBlockRequest
import app.spatio.client.models.CreateCommentRequest
import app.spatio.client.models.CreateNote400Response
import app.spatio.client.models.CreateNoteRequest
import app.spatio.client.models.EnableShareRequest
import app.spatio.client.models.MoveBlockRequest
import app.spatio.client.models.Note
import app.spatio.client.models.NoteListEnvelope
import app.spatio.client.models.PasswordRequiredError
import app.spatio.client.models.ShareSettings
import app.spatio.client.models.SuccessFlag
import app.spatio.client.models.UpdateBlockRequest
import app.spatio.client.models.UpdateCommentRequest
import app.spatio.client.models.UpdateNoteRequest

class NotesApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotesApi
        //val apiInstance = NotesApi()

        // to test createBlock
        should("test createBlock") {
            // uncomment below to test createBlock
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val createBlockRequest : CreateBlockRequest =  // CreateBlockRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : Block = apiInstance.createBlock(id, createBlockRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test createNote
        should("test createNote") {
            // uncomment below to test createNote
            //val createNoteRequest : CreateNoteRequest =  // CreateNoteRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val provider : kotlin.String = provider_example // kotlin.String | Provider id (e.g. `native-notes`, `notion`). Selects every connected account for the provider. Mutually exclusive with `accountId`. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : Note = apiInstance.createNote(createNoteRequest, accountId, provider, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test createNoteComment
        should("test createNoteComment") {
            // uncomment below to test createNoteComment
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val createCommentRequest : CreateCommentRequest =  // CreateCommentRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : CommentMutationResponse = apiInstance.createNoteComment(id, createCommentRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test deleteBlock
        should("test deleteBlock") {
            // uncomment below to test deleteBlock
            //val id : kotlin.String = id_example // kotlin.String | Block id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SuccessFlag = apiInstance.deleteBlock(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test deleteNote
        should("test deleteNote") {
            // uncomment below to test deleteNote
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SuccessFlag = apiInstance.deleteNote(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test deleteNoteComment
        should("test deleteNoteComment") {
            // uncomment below to test deleteNoteComment
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val commentId : kotlin.String = commentId_example // kotlin.String | Comment id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SuccessFlag = apiInstance.deleteNoteComment(id, commentId, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test disableNoteShare
        should("test disableNoteShare") {
            // uncomment below to test disableNoteShare
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //apiInstance.disableNoteShare(id, accountId, xWorkspaceID)
        }

        // to test enableNoteShare
        should("test enableNoteShare") {
            // uncomment below to test enableNoteShare
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val enableShareRequest : EnableShareRequest =  // EnableShareRequest | 
            //val result : ShareSettings = apiInstance.enableNoteShare(id, accountId, xWorkspaceID, enableShareRequest)
            //result shouldBe ("TODO")
        }

        // to test getBlock
        should("test getBlock") {
            // uncomment below to test getBlock
            //val id : kotlin.String = id_example // kotlin.String | Block id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : Block = apiInstance.getBlock(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getNote
        should("test getNote") {
            // uncomment below to test getNote
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : Note = apiInstance.getNote(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getNoteComment
        should("test getNoteComment") {
            // uncomment below to test getNoteComment
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val commentId : kotlin.String = commentId_example // kotlin.String | Comment id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : CommentResponse = apiInstance.getNoteComment(id, commentId, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getNoteShareSettings
        should("test getNoteShareSettings") {
            // uncomment below to test getNoteShareSettings
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : ShareSettings = apiInstance.getNoteShareSettings(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test getPublicNote
        should("test getPublicNote") {
            // uncomment below to test getPublicNote
            //val token : kotlin.String = token_example // kotlin.String | Opaque public-share token.
            //val password : kotlin.String = password_example // kotlin.String | Optional viewer password.
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getPublicNote(token, password)
            //result shouldBe ("TODO")
        }

        // to test listBlocks
        should("test listBlocks") {
            // uncomment below to test listBlocks
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val parentId : kotlin.String = parentId_example // kotlin.String | Filter to children of this block id. Omit to list root-level blocks. 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val offset : kotlin.Int = 56 // kotlin.Int | 
            //val result : BlockListResponse = apiInstance.listBlocks(id, accountId, xWorkspaceID, parentId, limit, offset)
            //result shouldBe ("TODO")
        }

        // to test listNoteComments
        should("test listNoteComments") {
            // uncomment below to test listNoteComments
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : CommentListResponse = apiInstance.listNoteComments(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test listNotes
        should("test listNotes") {
            // uncomment below to test listNotes
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val provider : kotlin.String = provider_example // kotlin.String | Provider id (e.g. `native-notes`, `notion`). Selects every connected account for the provider. Mutually exclusive with `accountId`. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val archived : kotlin.Boolean = true // kotlin.Boolean | When `true`, return archived notes instead of active ones.
            //val parentId : kotlin.String = parentId_example // kotlin.String | Filter to notes nested under this parent note id.
            //val tags : kotlin.collections.List<kotlin.String> =  // kotlin.collections.List<kotlin.String> | Repeatable. Filter to notes carrying every tag listed.
            //val limit : kotlin.Int = 56 // kotlin.Int | Max items to return. Defaults to 50.
            //val offset : kotlin.Int = 56 // kotlin.Int | Number of items to skip.
            //val sortBy : kotlin.String = sortBy_example // kotlin.String | Sort field. Provider-dependent; the native provider supports `updated_at`, `created_at`, `title`. 
            //val sortOrder : kotlin.String = sortOrder_example // kotlin.String | 
            //val result : NoteListEnvelope = apiInstance.listNotes(accountId, provider, xWorkspaceID, archived, parentId, tags, limit, offset, sortBy, sortOrder)
            //result shouldBe ("TODO")
        }

        // to test moveBlock
        should("test moveBlock") {
            // uncomment below to test moveBlock
            //val id : kotlin.String = id_example // kotlin.String | Block id.
            //val moveBlockRequest : MoveBlockRequest =  // MoveBlockRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : SuccessFlag = apiInstance.moveBlock(id, moveBlockRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test rotateNoteShareToken
        should("test rotateNoteShareToken") {
            // uncomment below to test rotateNoteShareToken
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : ShareSettings = apiInstance.rotateNoteShareToken(id, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test updateBlock
        should("test updateBlock") {
            // uncomment below to test updateBlock
            //val id : kotlin.String = id_example // kotlin.String | Block id.
            //val updateBlockRequest : UpdateBlockRequest =  // UpdateBlockRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : Block = apiInstance.updateBlock(id, updateBlockRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test updateNote
        should("test updateNote") {
            // uncomment below to test updateNote
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val updateNoteRequest : UpdateNoteRequest =  // UpdateNoteRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : Note = apiInstance.updateNote(id, updateNoteRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test updateNoteComment
        should("test updateNoteComment") {
            // uncomment below to test updateNoteComment
            //val id : kotlin.String = id_example // kotlin.String | Note id.
            //val commentId : kotlin.String = commentId_example // kotlin.String | Comment id.
            //val updateCommentRequest : UpdateCommentRequest =  // UpdateCommentRequest | 
            //val accountId : kotlin.String = accountId_example // kotlin.String | Connected-account row id. Selects which provider account this request targets when more than one is connected. Mutually exclusive with `provider`. If omitted on a list endpoint the call fans out across every connected account. 
            //val xWorkspaceID : kotlin.String = xWorkspaceID_example // kotlin.String | Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
            //val result : CommentMutationResponse = apiInstance.updateNoteComment(id, commentId, updateCommentRequest, accountId, xWorkspaceID)
            //result shouldBe ("TODO")
        }

        // to test workspaceCreateNote
        should("test workspaceCreateNote") {
            // uncomment below to test workspaceCreateNote
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceCreateNote(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceCreateNoteBlock
        should("test workspaceCreateNoteBlock") {
            // uncomment below to test workspaceCreateNoteBlock
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceCreateNoteBlock(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceDeleteNote
        should("test workspaceDeleteNote") {
            // uncomment below to test workspaceDeleteNote
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceDeleteNote(org, workspace, id)
        }

        // to test workspaceDeleteNoteBlock
        should("test workspaceDeleteNoteBlock") {
            // uncomment below to test workspaceDeleteNoteBlock
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceDeleteNoteBlock(org, workspace, id)
        }

        // to test workspaceGetNote
        should("test workspaceGetNote") {
            // uncomment below to test workspaceGetNote
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetNote(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceGetNoteBlock
        should("test workspaceGetNoteBlock") {
            // uncomment below to test workspaceGetNoteBlock
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceGetNoteBlock(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceListNoteBlocks
        should("test workspaceListNoteBlocks") {
            // uncomment below to test workspaceListNoteBlocks
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListNoteBlocks(org, workspace, id)
            //result shouldBe ("TODO")
        }

        // to test workspaceListNotes
        should("test workspaceListNotes") {
            // uncomment below to test workspaceListNotes
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListNotes(org, workspace)
            //result shouldBe ("TODO")
        }

        // to test workspaceMoveNoteBlock
        should("test workspaceMoveNoteBlock") {
            // uncomment below to test workspaceMoveNoteBlock
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceMoveNoteBlock(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceUpdateNote
        should("test workspaceUpdateNote") {
            // uncomment below to test workspaceUpdateNote
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdateNote(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceUpdateNoteBlock
        should("test workspaceUpdateNoteBlock") {
            // uncomment below to test workspaceUpdateNoteBlock
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdateNoteBlock(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

    }
}
