/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.NotificationsApi
import app.spatio.client.models.ApiError

class NotificationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationsApi
        //val apiInstance = NotificationsApi()

        // to test getNotificationPreferences
        should("test getNotificationPreferences") {
            // uncomment below to test getNotificationPreferences
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.getNotificationPreferences()
            //result shouldBe ("TODO")
        }

        // to test updateNotificationPreferences
        should("test updateNotificationPreferences") {
            // uncomment below to test updateNotificationPreferences
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.updateNotificationPreferences(requestBody)
            //result shouldBe ("TODO")
        }

    }
}
