/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.PersonalAccessTokensApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.CreatePATRequest
import app.spatio.client.models.CreatePATResponse
import app.spatio.client.models.PATListResponse
import app.spatio.client.models.PATScopesResponse
import app.spatio.client.models.PersonalAccessToken
import app.spatio.client.models.UpdatePATRequest

class PersonalAccessTokensApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PersonalAccessTokensApi
        //val apiInstance = PersonalAccessTokensApi()

        // to test createPersonalAccessToken
        should("test createPersonalAccessToken") {
            // uncomment below to test createPersonalAccessToken
            //val createPATRequest : CreatePATRequest =  // CreatePATRequest | 
            //val result : CreatePATResponse = apiInstance.createPersonalAccessToken(createPATRequest)
            //result shouldBe ("TODO")
        }

        // to test listAvailablePATScopes
        should("test listAvailablePATScopes") {
            // uncomment below to test listAvailablePATScopes
            //val result : PATScopesResponse = apiInstance.listAvailablePATScopes()
            //result shouldBe ("TODO")
        }

        // to test listPersonalAccessTokens
        should("test listPersonalAccessTokens") {
            // uncomment below to test listPersonalAccessTokens
            //val result : PATListResponse = apiInstance.listPersonalAccessTokens()
            //result shouldBe ("TODO")
        }

        // to test revokePersonalAccessToken
        should("test revokePersonalAccessToken") {
            // uncomment below to test revokePersonalAccessToken
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.revokePersonalAccessToken(id)
        }

        // to test updatePersonalAccessToken
        should("test updatePersonalAccessToken") {
            // uncomment below to test updatePersonalAccessToken
            //val id : kotlin.String = id_example // kotlin.String | 
            //val updatePATRequest : UpdatePATRequest =  // UpdatePATRequest | 
            //val result : PersonalAccessToken = apiInstance.updatePersonalAccessToken(id, updatePATRequest)
            //result shouldBe ("TODO")
        }

        // to test workspaceCreatePAT
        should("test workspaceCreatePAT") {
            // uncomment below to test workspaceCreatePAT
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceCreatePAT(org, workspace, requestBody)
            //result shouldBe ("TODO")
        }

        // to test workspaceListPATs
        should("test workspaceListPATs") {
            // uncomment below to test workspaceListPATs
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceListPATs(org, workspace)
            //result shouldBe ("TODO")
        }

        // to test workspaceRevokePAT
        should("test workspaceRevokePAT") {
            // uncomment below to test workspaceRevokePAT
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.workspaceRevokePAT(org, workspace, id)
        }

        // to test workspaceUpdatePAT
        should("test workspaceUpdatePAT") {
            // uncomment below to test workspaceUpdatePAT
            //val org : kotlin.String = org_example // kotlin.String | 
            //val workspace : kotlin.String = workspace_example // kotlin.String | 
            //val id : kotlin.String = id_example // kotlin.String | 
            //val requestBody : kotlin.collections.Map<kotlin.String, kotlin.Any> = Object // kotlin.collections.Map<kotlin.String, kotlin.Any> | 
            //val result : kotlin.collections.Map<kotlin.String, kotlin.Any> = apiInstance.workspaceUpdatePAT(org, workspace, id, requestBody)
            //result shouldBe ("TODO")
        }

    }
}
