/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.RealtimeApi
import app.spatio.client.models.IssueCollaborationToken200Response
import app.spatio.client.models.IssueCollaborationTokenRequest

class RealtimeApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RealtimeApi
        //val apiInstance = RealtimeApi()

        // to test issueCollaborationToken
        should("test issueCollaborationToken") {
            // uncomment below to test issueCollaborationToken
            //val issueCollaborationTokenRequest : IssueCollaborationTokenRequest =  // IssueCollaborationTokenRequest | 
            //val result : IssueCollaborationToken200Response = apiInstance.issueCollaborationToken(issueCollaborationTokenRequest)
            //result shouldBe ("TODO")
        }

    }
}
