/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.apis.RecommendationsApi
import app.spatio.client.models.ApiError
import app.spatio.client.models.ProposeRecommendationRequest
import app.spatio.client.models.Recommendation
import app.spatio.client.models.RecommendationListResponse
import app.spatio.client.models.UpdateRecommendationStatusRequest

class RecommendationsApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecommendationsApi
        //val apiInstance = RecommendationsApi()

        // to test deleteRecommendation
        should("test deleteRecommendation") {
            // uncomment below to test deleteRecommendation
            //val id : kotlin.String = id_example // kotlin.String | 
            //apiInstance.deleteRecommendation(id)
        }

        // to test getRecommendation
        should("test getRecommendation") {
            // uncomment below to test getRecommendation
            //val id : kotlin.String = id_example // kotlin.String | 
            //val result : Recommendation = apiInstance.getRecommendation(id)
            //result shouldBe ("TODO")
        }

        // to test listRecommendations
        should("test listRecommendations") {
            // uncomment below to test listRecommendations
            //val workspaceId : kotlin.String = workspaceId_example // kotlin.String | 
            //val status : kotlin.String = status_example // kotlin.String | 
            //val limit : kotlin.Int = 56 // kotlin.Int | 
            //val result : RecommendationListResponse = apiInstance.listRecommendations(workspaceId, status, limit)
            //result shouldBe ("TODO")
        }

        // to test proposeRecommendation
        should("test proposeRecommendation") {
            // uncomment below to test proposeRecommendation
            //val proposeRecommendationRequest : ProposeRecommendationRequest =  // ProposeRecommendationRequest | 
            //val result : Recommendation = apiInstance.proposeRecommendation(proposeRecommendationRequest)
            //result shouldBe ("TODO")
        }

        // to test updateRecommendationStatus
        should("test updateRecommendationStatus") {
            // uncomment below to test updateRecommendationStatus
            //val id : kotlin.String = id_example // kotlin.String | 
            //val updateRecommendationStatusRequest : UpdateRecommendationStatusRequest =  // UpdateRecommendationStatusRequest | 
            //val result : Recommendation = apiInstance.updateRecommendationStatus(id, updateRecommendationStatusRequest)
            //result shouldBe ("TODO")
        }

    }
}
