/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.AccountStatus
import app.spatio.client.models.AccountError

class AccountStatusTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AccountStatus
        //val modelInstance = AccountStatus()

        // to test the property `provider` - Provider id (e.g. `native-notes`, `notion`, `google-keep`).
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `accountId` - Connected-account row id.
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `status` - - `ok` — provider call returned without error. - `error` — provider call failed; details in `error`. - `skipped` — connection was filtered out before the provider   call ran. Reserved; not currently emitted by the runtime. 
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `accountName` - Human-readable label for the account, when available.
        should("test accountName") {
            // uncomment below to test the property
            //modelInstance.accountName shouldBe ("TODO")
        }

        // to test the property `error`
        should("test error") {
            // uncomment below to test the property
            //modelInstance.error shouldBe ("TODO")
        }

        // to test the property `nextPageToken` - Provider-specific cursor for the next page, if any.
        should("test nextPageToken") {
            // uncomment below to test the property
            //modelInstance.nextPageToken shouldBe ("TODO")
        }

    }
}
