/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.BlockListResponse
import app.spatio.client.models.Block

class BlockListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BlockListResponse
        //val modelInstance = BlockListResponse()

        // to test the property `blocks`
        should("test blocks") {
            // uncomment below to test the property
            //modelInstance.blocks shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
