/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.BulkDeleteEmailsResponse
import app.spatio.client.models.BulkArchiveResponseFailedInner

class BulkDeleteEmailsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BulkDeleteEmailsResponse
        //val modelInstance = BulkDeleteEmailsResponse()

        // to test the property `success`
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

        // to test the property `deleted`
        should("test deleted") {
            // uncomment below to test the property
            //modelInstance.deleted shouldBe ("TODO")
        }

        // to test the property `failed`
        should("test failed") {
            // uncomment below to test the property
            //modelInstance.failed shouldBe ("TODO")
        }

    }
}
