/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.CalendarCapabilitiesResponse

class CalendarCapabilitiesResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CalendarCapabilitiesResponse
        //val modelInstance = CalendarCapabilitiesResponse()

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `providerId`
        should("test providerId") {
            // uncomment below to test the property
            //modelInstance.providerId shouldBe ("TODO")
        }

        // to test the property `capabilities` - Per-account feature gate. The renderer reads these to enable/ disable form fields (recurrence pickers, attendee inputs, etc.) based on what the underlying provider supports. 
        should("test capabilities") {
            // uncomment below to test the property
            //modelInstance.capabilities shouldBe ("TODO")
        }

    }
}
