/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.CallRecordingListResponse
import app.spatio.client.models.CallRecording

class CallRecordingListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CallRecordingListResponse
        //val modelInstance = CallRecordingListResponse()

        // to test the property `recordings`
        should("test recordings") {
            // uncomment below to test the property
            //modelInstance.recordings shouldBe ("TODO")
        }

    }
}
