/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.ChatActionDefinition

class ChatActionDefinitionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ChatActionDefinition
        //val modelInstance = ChatActionDefinition()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `platform`
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `category` - Common values: `read`, `write`, `delete`, `manage`, `sync`.
        should("test category") {
            // uncomment below to test the property
            //modelInstance.category shouldBe ("TODO")
        }

        // to test the property `inputType`
        should("test inputType") {
            // uncomment below to test the property
            //modelInstance.inputType shouldBe ("TODO")
        }

        // to test the property `outputType`
        should("test outputType") {
            // uncomment below to test the property
            //modelInstance.outputType shouldBe ("TODO")
        }

        // to test the property `scopes` - `null` when no scopes are declared (Go nil-slice).
        should("test scopes") {
            // uncomment below to test the property
            //modelInstance.scopes shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

    }
}
