/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.ConnectionListResponse
import app.spatio.client.models.SpatioConnection

class ConnectionListResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConnectionListResponse
        //val modelInstance = ConnectionListResponse()

        // to test the property `connections`
        should("test connections") {
            // uncomment below to test the property
            //modelInstance.connections shouldBe ("TODO")
        }

        // to test the property `categories`
        should("test categories") {
            // uncomment below to test the property
            //modelInstance.categories shouldBe ("TODO")
        }

    }
}
