/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.CreateSlideElementRequest

class CreateSlideElementRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateSlideElementRequest
        //val modelInstance = CreateSlideElementRequest()

        // to test the property `elementType`
        should("test elementType") {
            // uncomment below to test the property
            //modelInstance.elementType shouldBe ("TODO")
        }

        // to test the property `content`
        should("test content") {
            // uncomment below to test the property
            //modelInstance.content shouldBe ("TODO")
        }

        // to test the property `x`
        should("test x") {
            // uncomment below to test the property
            //modelInstance.x shouldBe ("TODO")
        }

        // to test the property `y`
        should("test y") {
            // uncomment below to test the property
            //modelInstance.y shouldBe ("TODO")
        }

        // to test the property `width`
        should("test width") {
            // uncomment below to test the property
            //modelInstance.width shouldBe ("TODO")
        }

        // to test the property `height`
        should("test height") {
            // uncomment below to test the property
            //modelInstance.height shouldBe ("TODO")
        }

        // to test the property `rotation`
        should("test rotation") {
            // uncomment below to test the property
            //modelInstance.rotation shouldBe ("TODO")
        }

        // to test the property `zIndex`
        should("test zIndex") {
            // uncomment below to test the property
            //modelInstance.zIndex shouldBe ("TODO")
        }

    }
}
