/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.CreateTaskRequest

class CreateTaskRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateTaskRequest
        //val modelInstance = CreateTaskRequest()

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `dueDate`
        should("test dueDate") {
            // uncomment below to test the property
            //modelInstance.dueDate shouldBe ("TODO")
        }

        // to test the property `priority`
        should("test priority") {
            // uncomment below to test the property
            //modelInstance.priority shouldBe ("TODO")
        }

        // to test the property `labels`
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `tags`
        should("test tags") {
            // uncomment below to test the property
            //modelInstance.tags shouldBe ("TODO")
        }

        // to test the property `assigneeId`
        should("test assigneeId") {
            // uncomment below to test the property
            //modelInstance.assigneeId shouldBe ("TODO")
        }

        // to test the property `parentTaskId`
        should("test parentTaskId") {
            // uncomment below to test the property
            //modelInstance.parentTaskId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `sourcePlatform`
        should("test sourcePlatform") {
            // uncomment below to test the property
            //modelInstance.sourcePlatform shouldBe ("TODO")
        }

        // to test the property `sourceId`
        should("test sourceId") {
            // uncomment below to test the property
            //modelInstance.sourceId shouldBe ("TODO")
        }

        // to test the property `accountId` - Optional override for the target connected account. May also be passed as `?accountId=`. 
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

    }
}
