/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.DMForwardRequest

class DMForwardRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DMForwardRequest
        //val modelInstance = DMForwardRequest()

        // to test the property `toDmId`
        should("test toDmId") {
            // uncomment below to test the property
            //modelInstance.toDmId shouldBe ("TODO")
        }

        // to test the property `toChannelId`
        should("test toChannelId") {
            // uncomment below to test the property
            //modelInstance.toChannelId shouldBe ("TODO")
        }

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

    }
}
