/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.DMMuteResponse

class DMMuteResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DMMuteResponse
        //val modelInstance = DMMuteResponse()

        // to test the property `mutedUntil`
        should("test mutedUntil") {
            // uncomment below to test the property
            //modelInstance.mutedUntil shouldBe ("TODO")
        }

    }
}
