/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.DMPinnedList

class DMPinnedListTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DMPinnedList
        //val modelInstance = DMPinnedList()

        // to test the property `pinned` - Provider-shaped pinned list.
        should("test pinned") {
            // uncomment below to test the property
            //modelInstance.pinned shouldBe ("TODO")
        }

    }
}
