/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.Draft
import app.spatio.client.models.AttachmentMeta

class DraftTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Draft
        //val modelInstance = Draft()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `messageId`
        should("test messageId") {
            // uncomment below to test the property
            //modelInstance.messageId shouldBe ("TODO")
        }

        // to test the property `html`
        should("test html") {
            // uncomment below to test the property
            //modelInstance.html shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `threadId`
        should("test threadId") {
            // uncomment below to test the property
            //modelInstance.threadId shouldBe ("TODO")
        }

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `cc`
        should("test cc") {
            // uncomment below to test the property
            //modelInstance.cc shouldBe ("TODO")
        }

        // to test the property `bcc`
        should("test bcc") {
            // uncomment below to test the property
            //modelInstance.bcc shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `body`
        should("test body") {
            // uncomment below to test the property
            //modelInstance.body shouldBe ("TODO")
        }

        // to test the property `attachments`
        should("test attachments") {
            // uncomment below to test the property
            //modelInstance.attachments shouldBe ("TODO")
        }

    }
}
