/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.FederatedSearchRequest

class FederatedSearchRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FederatedSearchRequest
        //val modelInstance = FederatedSearchRequest()

        // to test the property `query`
        should("test query") {
            // uncomment below to test the property
            //modelInstance.query shouldBe ("TODO")
        }

        // to test the property `platforms` - Subset to fan out to. Empty means all available platforms.
        should("test platforms") {
            // uncomment below to test the property
            //modelInstance.platforms shouldBe ("TODO")
        }

        // to test the property `limit`
        should("test limit") {
            // uncomment below to test the property
            //modelInstance.limit shouldBe ("TODO")
        }

        // to test the property `pageTokens` - Per-platform cursor for pagination.
        should("test pageTokens") {
            // uncomment below to test the property
            //modelInstance.pageTokens shouldBe ("TODO")
        }

        // to test the property `workspaceId`
        should("test workspaceId") {
            // uncomment below to test the property
            //modelInstance.workspaceId shouldBe ("TODO")
        }

        // to test the property `organizationId`
        should("test organizationId") {
            // uncomment below to test the property
            //modelInstance.organizationId shouldBe ("TODO")
        }

        // to test the property `includeShared`
        should("test includeShared") {
            // uncomment below to test the property
            //modelInstance.includeShared shouldBe ("TODO")
        }

        // to test the property `includeArchived`
        should("test includeArchived") {
            // uncomment below to test the property
            //modelInstance.includeArchived shouldBe ("TODO")
        }

    }
}
