/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.FederatedSearch200Response
import app.spatio.client.models.FederatedSearch200ResponseItemsInner
import app.spatio.client.models.FederatedSearch200ResponsePerPlatformValue

class FederatedSearch200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of FederatedSearch200Response
        //val modelInstance = FederatedSearch200Response()

        // to test the property `items`
        should("test items") {
            // uncomment below to test the property
            //modelInstance.items shouldBe ("TODO")
        }

        // to test the property `perPlatform`
        should("test perPlatform") {
            // uncomment below to test the property
            //modelInstance.perPlatform shouldBe ("TODO")
        }

        // to test the property `totalReturned`
        should("test totalReturned") {
            // uncomment below to test the property
            //modelInstance.totalReturned shouldBe ("TODO")
        }

        // to test the property `took` - Aggregate wall-clock time for the fan-out, e.g. \"120ms\".
        should("test took") {
            // uncomment below to test the property
            //modelInstance.took shouldBe ("TODO")
        }

        // to test the property `nextPageTokens`
        should("test nextPageTokens") {
            // uncomment below to test the property
            //modelInstance.nextPageTokens shouldBe ("TODO")
        }

        // to test the property `errors` - Per-platform errors. Other platforms still return results.
        should("test errors") {
            // uncomment below to test the property
            //modelInstance.errors shouldBe ("TODO")
        }

    }
}
