/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.JWK

class JWKTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of JWK
        //val modelInstance = JWK()

        // to test the property `kty`
        should("test kty") {
            // uncomment below to test the property
            //modelInstance.kty shouldBe ("TODO")
        }

        // to test the property `use`
        should("test use") {
            // uncomment below to test the property
            //modelInstance.use shouldBe ("TODO")
        }

        // to test the property `alg`
        should("test alg") {
            // uncomment below to test the property
            //modelInstance.alg shouldBe ("TODO")
        }

        // to test the property `kid`
        should("test kid") {
            // uncomment below to test the property
            //modelInstance.kid shouldBe ("TODO")
        }

        // to test the property `n` - Base64url-encoded RSA modulus.
        should("test n") {
            // uncomment below to test the property
            //modelInstance.n shouldBe ("TODO")
        }

        // to test the property `e` - Base64url-encoded RSA exponent. Almost always \"AQAB\".
        should("test e") {
            // uncomment below to test the property
            //modelInstance.e shouldBe ("TODO")
        }

    }
}
