/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.ListDraftsResponse
import app.spatio.client.models.Draft

class ListDraftsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListDraftsResponse
        //val modelInstance = ListDraftsResponse()

        // to test the property `drafts`
        should("test drafts") {
            // uncomment below to test the property
            //modelInstance.drafts shouldBe ("TODO")
        }

        // to test the property `total`
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `nextPageToken`
        should("test nextPageToken") {
            // uncomment below to test the property
            //modelInstance.nextPageToken shouldBe ("TODO")
        }

    }
}
