/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.Organization
import app.spatio.client.models.OrganizationWorkspacesInner

class OrganizationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Organization
        //val modelInstance = Organization()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `role` - The caller's role in this org (`owner`, `admin`, `billing_admin`, `member`).
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `logoUrl`
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

        // to test the property `memberCount`
        should("test memberCount") {
            // uncomment below to test the property
            //modelInstance.memberCount shouldBe ("TODO")
        }

        // to test the property `workspaceCount`
        should("test workspaceCount") {
            // uncomment below to test the property
            //modelInstance.workspaceCount shouldBe ("TODO")
        }

        // to test the property `workspaces` - Compact workspace summaries embedded in the org-list response.
        should("test workspaces") {
            // uncomment below to test the property
            //modelInstance.workspaces shouldBe ("TODO")
        }

    }
}
