/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.PreconfiguredAgent

class PreconfiguredAgentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PreconfiguredAgent
        //val modelInstance = PreconfiguredAgent()

        // to test the property `agentId`
        should("test agentId") {
            // uncomment below to test the property
            //modelInstance.agentId shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `tagline`
        should("test tagline") {
            // uncomment below to test the property
            //modelInstance.tagline shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `icon`
        should("test icon") {
            // uncomment below to test the property
            //modelInstance.icon shouldBe ("TODO")
        }

        // to test the property `hasAllTools`
        should("test hasAllTools") {
            // uncomment below to test the property
            //modelInstance.hasAllTools shouldBe ("TODO")
        }

        // to test the property `toolCount`
        should("test toolCount") {
            // uncomment below to test the property
            //modelInstance.toolCount shouldBe ("TODO")
        }

    }
}
