/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.Slide

class SlideTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Slide
        //val modelInstance = Slide()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `presentationId`
        should("test presentationId") {
            // uncomment below to test the property
            //modelInstance.presentationId shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `position` - Zero-based position within the presentation.
        should("test position") {
            // uncomment below to test the property
            //modelInstance.position shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `provider`
        should("test provider") {
            // uncomment below to test the property
            //modelInstance.provider shouldBe ("TODO")
        }

        // to test the property `accountId`
        should("test accountId") {
            // uncomment below to test the property
            //modelInstance.accountId shouldBe ("TODO")
        }

        // to test the property `notes` - Speaker notes.
        should("test notes") {
            // uncomment below to test the property
            //modelInstance.notes shouldBe ("TODO")
        }

        // to test the property `layout` - Free-form layout id. Provider-specific (`title`, `two-column`, `image-left`, custom). Not enumerated to avoid forcing a breaking change every time a provider adds one. 
        should("test layout") {
            // uncomment below to test the property
            //modelInstance.layout shouldBe ("TODO")
        }

        // to test the property `backgroundColor`
        should("test backgroundColor") {
            // uncomment below to test the property
            //modelInstance.backgroundColor shouldBe ("TODO")
        }

        // to test the property `backgroundImageUrl`
        should("test backgroundImageUrl") {
            // uncomment below to test the property
            //modelInstance.backgroundImageUrl shouldBe ("TODO")
        }

        // to test the property `textColor`
        should("test textColor") {
            // uncomment below to test the property
            //modelInstance.textColor shouldBe ("TODO")
        }

        // to test the property `transition` - Free-form transition id.
        should("test transition") {
            // uncomment below to test the property
            //modelInstance.transition shouldBe ("TODO")
        }

    }
}
