/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.SpatioCall

class SpatioCallTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SpatioCall
        //val modelInstance = SpatioCall()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `title`
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `status`
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `hostUserId`
        should("test hostUserId") {
            // uncomment below to test the property
            //modelInstance.hostUserId shouldBe ("TODO")
        }

        // to test the property `workspaceId`
        should("test workspaceId") {
            // uncomment below to test the property
            //modelInstance.workspaceId shouldBe ("TODO")
        }

        // to test the property `roomId`
        should("test roomId") {
            // uncomment below to test the property
            //modelInstance.roomId shouldBe ("TODO")
        }

        // to test the property `participants`
        should("test participants") {
            // uncomment below to test the property
            //modelInstance.participants shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `startedAt`
        should("test startedAt") {
            // uncomment below to test the property
            //modelInstance.startedAt shouldBe ("TODO")
        }

        // to test the property `endedAt`
        should("test endedAt") {
            // uncomment below to test the property
            //modelInstance.endedAt shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

    }
}
