/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import app.spatio.client.models.Workspace
import app.spatio.client.models.WorkspaceOrganization

class WorkspaceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Workspace
        //val modelInstance = Workspace()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `slug`
        should("test slug") {
            // uncomment below to test the property
            //modelInstance.slug shouldBe ("TODO")
        }

        // to test the property `description`
        should("test description") {
            // uncomment below to test the property
            //modelInstance.description shouldBe ("TODO")
        }

        // to test the property `logoUrl`
        should("test logoUrl") {
            // uncomment below to test the property
            //modelInstance.logoUrl shouldBe ("TODO")
        }

        // to test the property `organizationId`
        should("test organizationId") {
            // uncomment below to test the property
            //modelInstance.organizationId shouldBe ("TODO")
        }

        // to test the property `organization`
        should("test organization") {
            // uncomment below to test the property
            //modelInstance.organization shouldBe ("TODO")
        }

        // to test the property `role` - The caller's role in this workspace (`owner`, `admin`, `member`, `guest`).
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

        // to test the property `settings` - Per-workspace settings. Currently emitted as either an object (`{language, timezone, ...}`) on `GET /v1/workspaces/{id}` or a JSON-encoded string on `GET /v1/organizations/{id}/workspaces`. Treat as opaque and parse defensively. 
        should("test settings") {
            // uncomment below to test the property
            //modelInstance.settings shouldBe ("TODO")
        }

        // to test the property `isDefault`
        should("test isDefault") {
            // uncomment below to test the property
            //modelInstance.isDefault shouldBe ("TODO")
        }

        // to test the property `memberCount`
        should("test memberCount") {
            // uncomment below to test the property
            //modelInstance.memberCount shouldBe ("TODO")
        }

        // to test the property `billingTier`
        should("test billingTier") {
            // uncomment below to test the property
            //modelInstance.billingTier shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
