/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One of the candidates returned alongside an `ambiguous_account` error so the client can prompt the user to pick a target account. 
 *
 * @param provider 
 * @param accountId 
 * @param accountName 
 */


data class AccountChoice (

    @Json(name = "provider")
    val provider: kotlin.String,

    @Json(name = "accountId")
    val accountId: kotlin.String,

    @Json(name = "accountName")
    val accountName: kotlin.String? = null

) {


}

