/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * `GET /v1/accounts` returns `{accounts_by_platform, total_accounts}` on production today. Schema kept open until the consumers migrate to a flat `accounts` array. 
 *
 * @param accountsByPlatform 
 * @param totalAccounts 
 * @param accounts 
 */


data class AccountListResponse (

    @Json(name = "accounts_by_platform")
    val accountsByPlatform: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "total_accounts")
    val totalAccounts: kotlin.Int? = null,

    @Json(name = "accounts")
    val accounts: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null

) {


}

