/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Per-tier capability + quota envelope. Numeric quotas use 0/-1 idioms; treat large negatives as \"unlimited.\"
 *
 * @param tier 
 * @param dailyApiCalls 
 * @param maxConnectedAccounts 
 * @param maxEmailSendsPerDay 
 * @param maxNotes 
 * @param maxSheets 
 * @param maxSlides 
 * @param maxFiles 
 * @param maxTasks 
 * @param maxTeamMembers 
 * @param maxWorkspaces 
 * @param storageGb 
 * @param hasAutomations 
 * @param hasAdvancedAutomations 
 * @param hasFullApiAccess 
 */


data class AccountTierDetails (

    @Json(name = "tier")
    val tier: kotlin.String,

    @Json(name = "daily_api_calls")
    val dailyApiCalls: kotlin.Int? = null,

    @Json(name = "max_connected_accounts")
    val maxConnectedAccounts: kotlin.Int? = null,

    @Json(name = "max_email_sends_per_day")
    val maxEmailSendsPerDay: kotlin.Int? = null,

    @Json(name = "max_notes")
    val maxNotes: kotlin.Int? = null,

    @Json(name = "max_sheets")
    val maxSheets: kotlin.Int? = null,

    @Json(name = "max_slides")
    val maxSlides: kotlin.Int? = null,

    @Json(name = "max_files")
    val maxFiles: kotlin.Int? = null,

    @Json(name = "max_tasks")
    val maxTasks: kotlin.Int? = null,

    @Json(name = "max_team_members")
    val maxTeamMembers: kotlin.Int? = null,

    @Json(name = "max_workspaces")
    val maxWorkspaces: kotlin.Int? = null,

    @Json(name = "storage_gb")
    val storageGb: kotlin.Int? = null,

    @Json(name = "has_automations")
    val hasAutomations: kotlin.Boolean? = null,

    @Json(name = "has_advanced_automations")
    val hasAdvancedAutomations: kotlin.Boolean? = null,

    @Json(name = "has_full_api_access")
    val hasFullApiAccess: kotlin.Boolean? = null

) {


}

