/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Subscription summary. `tier` is the canonical billing tier (uppercased: `FREE`, `PRO`, `MAX`, `ENTERPRISE`); `display_name` is the lowercase user-facing label. 
 *
 * @param tier 
 * @param displayName 
 * @param subscriptionStatus Stripe subscription state: `ACTIVE`, `TRIALING`, `PAST_DUE`, `CANCELED`, etc.
 * @param trialEndsAt 
 */


data class AccountPlan (

    @Json(name = "tier")
    val tier: kotlin.String,

    @Json(name = "display_name")
    val displayName: kotlin.String,

    /* Stripe subscription state: `ACTIVE`, `TRIALING`, `PAST_DUE`, `CANCELED`, etc. */
    @Json(name = "subscription_status")
    val subscriptionStatus: kotlin.String,

    @Json(name = "trial_ends_at")
    val trialEndsAt: java.time.OffsetDateTime? = null

) {


}

