/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.AccountError

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Outcome of one connected account's contribution to a fan-out call. Every connection that participated appears in `Envelope.accounts` exactly once, regardless of whether it succeeded, errored, or returned zero items. 
 *
 * @param provider Provider id (e.g. `native-notes`, `notion`, `google-keep`).
 * @param accountId Connected-account row id.
 * @param status - `ok` — provider call returned without error. - `error` — provider call failed; details in `error`. - `skipped` — connection was filtered out before the provider   call ran. Reserved; not currently emitted by the runtime. 
 * @param accountName Human-readable label for the account, when available.
 * @param error 
 * @param nextPageToken Provider-specific cursor for the next page, if any.
 */


data class AccountStatus (

    /* Provider id (e.g. `native-notes`, `notion`, `google-keep`). */
    @Json(name = "provider")
    val provider: kotlin.String,

    /* Connected-account row id. */
    @Json(name = "accountId")
    val accountId: kotlin.String,

    /* - `ok` — provider call returned without error. - `error` — provider call failed; details in `error`. - `skipped` — connection was filtered out before the provider   call ran. Reserved; not currently emitted by the runtime.  */
    @Json(name = "status")
    val status: AccountStatus.Status,

    /* Human-readable label for the account, when available. */
    @Json(name = "accountName")
    val accountName: kotlin.String? = null,

    @Json(name = "error")
    val error: AccountError? = null,

    /* Provider-specific cursor for the next page, if any. */
    @Json(name = "nextPageToken")
    val nextPageToken: kotlin.String? = null

) {

    /**
     * - `ok` — provider call returned without error. - `error` — provider call failed; details in `error`. - `skipped` — connection was filtered out before the provider   call ran. Reserved; not currently emitted by the runtime. 
     *
     * Values: ok,error,skipped
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "ok") ok("ok"),
        @Json(name = "error") error("error"),
        @Json(name = "skipped") skipped("skipped");
    }

}

