/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.AccountChoice

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Returned when the caller's request matches more than one connected account and no `accountId` query param disambiguates which one to target. The `accounts` array enumerates the candidates so the client can prompt the user to pick. 
 *
 * @param error Human-readable error message.
 * @param code Machine-readable error code. Stable across releases for the canonical codes (`ambiguous_account`, `no_notes_provider`, `note_not_found`). Absent for generic errors. 
 * @param accounts 
 */


data class AmbiguousAccountError (

    /* Human-readable error message. */
    @Json(name = "error")
    val error: kotlin.String,

    /* Machine-readable error code. Stable across releases for the canonical codes (`ambiguous_account`, `no_notes_provider`, `note_not_found`). Absent for generic errors.  */
    @Json(name = "code")
    val code: kotlin.String? = null,

    @Json(name = "accounts")
    val accounts: kotlin.collections.List<AccountChoice>? = null

) {


}

