/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.AttendeeRole
import app.spatio.client.models.AttendeeStatus

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param status 
 * @param role 
 * @param optional Legacy boolean — superseded by `role` (`role: optional` carries the same signal). Kept on the wire for client compatibility. 
 * @param name 
 * @param comment 
 * @param additionalGuests 
 */


data class Attendee (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "status")
    val status: AttendeeStatus,

    @Json(name = "role")
    val role: AttendeeRole,

    /* Legacy boolean — superseded by `role` (`role: optional` carries the same signal). Kept on the wire for client compatibility.  */
    @Json(name = "optional")
    val optional: kotlin.Boolean,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "comment")
    val comment: kotlin.String? = null,

    @Json(name = "additional_guests")
    val additionalGuests: kotlin.Int? = null

) {


}

