/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Discriminator for block types. The structure of `content` varies by type (e.g. `paragraph` carries `richText`; `code` carries `richText` + `language`; `image` carries `url` + `caption` + `altText`). 
 *
 * Values: paragraph,heading_1,heading_2,heading_3,bulleted_list_item,numbered_list_item,to_do,toggle,code,quote,callout,divider,image,video,file,embed,table,table_row,column_list,column,equation,breadcrumb,table_of_contents
 */

@JsonClass(generateAdapter = false)
enum class BlockType(val value: kotlin.String) {

    @Json(name = "paragraph")
    paragraph("paragraph"),

    @Json(name = "heading_1")
    heading_1("heading_1"),

    @Json(name = "heading_2")
    heading_2("heading_2"),

    @Json(name = "heading_3")
    heading_3("heading_3"),

    @Json(name = "bulleted_list_item")
    bulleted_list_item("bulleted_list_item"),

    @Json(name = "numbered_list_item")
    numbered_list_item("numbered_list_item"),

    @Json(name = "to_do")
    to_do("to_do"),

    @Json(name = "toggle")
    toggle("toggle"),

    @Json(name = "code")
    code("code"),

    @Json(name = "quote")
    quote("quote"),

    @Json(name = "callout")
    callout("callout"),

    @Json(name = "divider")
    divider("divider"),

    @Json(name = "image")
    image("image"),

    @Json(name = "video")
    video("video"),

    @Json(name = "file")
    file("file"),

    @Json(name = "embed")
    embed("embed"),

    @Json(name = "table")
    table("table"),

    @Json(name = "table_row")
    table_row("table_row"),

    @Json(name = "column_list")
    column_list("column_list"),

    @Json(name = "column")
    column("column"),

    @Json(name = "equation")
    equation("equation"),

    @Json(name = "breadcrumb")
    breadcrumb("breadcrumb"),

    @Json(name = "table_of_contents")
    table_of_contents("table_of_contents");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is BlockType) "$data" else null

        /**
         * Returns a valid [BlockType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): BlockType? = data?.let {
          val normalizedData = "$it".lowercase()
          entries.firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

