/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.BlockContent
import app.spatio.client.models.BlockType

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param noteId 
 * @param type 
 * @param content 
 * @param position Order within the parent (0-indexed).
 * @param hasChildren 
 * @param createdAt 
 * @param updatedAt 
 * @param parentId 
 * @param properties 
 */


data class Block (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "noteId")
    val noteId: kotlin.String,

    @Json(name = "type")
    val type: BlockType,

    @Json(name = "content")
    val content: BlockContent,

    /* Order within the parent (0-indexed). */
    @Json(name = "position")
    val position: kotlin.Int,

    @Json(name = "hasChildren")
    val hasChildren: kotlin.Boolean,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    @Json(name = "parentId")
    val parentId: kotlin.String? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

