/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.UpdateTaskRequest

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Apply the same `updates` payload to every id. Same parallel AccountIDs convention as bulk delete. 
 *
 * @param taskIds 
 * @param updates 
 * @param accountIds 
 * @param accountId 
 */


data class BulkUpdateTasksRequest (

    @Json(name = "taskIds")
    val taskIds: kotlin.collections.List<kotlin.String>,

    @Json(name = "updates")
    val updates: UpdateTaskRequest,

    @Json(name = "accountIds")
    val accountIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "accountId")
    val accountId: kotlin.String? = null

) {


}

