/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Either `fileIds` (with optional parallel `accountIds`) for multi-file delete, or `fileId` (with optional `accountId`) for the single-file fallback. `fileIds` wins when both are set. 
 *
 * @param fileIds 
 * @param accountIds Parallel slice with fileIds — accountIds[i] targets fileIds[i].
 * @param fileId 
 * @param accountId 
 */


data class BulkDeleteFilesRequest (

    @Json(name = "fileIds")
    val fileIds: kotlin.collections.List<kotlin.String>? = null,

    /* Parallel slice with fileIds — accountIds[i] targets fileIds[i]. */
    @Json(name = "accountIds")
    val accountIds: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "fileId")
    val fileId: kotlin.String? = null,

    @Json(name = "accountId")
    val accountId: kotlin.String? = null

) {


}

