/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Bulk shorthand for setting read state on many messages at once. `messageIds` accepts an array; the production handler also accepts a bare string for renderer-compat but the spec models the array shape only. `read` defaults to `true` when omitted. 
 *
 * @param messageIds 
 * @param accountId 
 * @param read 
 */


data class BulkMarkReadRequest (

    @Json(name = "messageIds")
    val messageIds: kotlin.collections.List<kotlin.String>,

    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    @Json(name = "read")
    val read: kotlin.Boolean? = true

) {


}

