/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Returned by `POST /v1/calendar/sync`. Status code is `202` by default (sync jobs queued); `200` when called with `?wait=true` and all jobs finish within the 10-second polling budget. 
 *
 * @param enqueued 
 * @param jobs 
 * @param waited 
 * @param timedOut 
 * @param errors 
 */


data class CalendarSyncResponse (

    @Json(name = "enqueued")
    val enqueued: kotlin.Int,

    @Json(name = "jobs")
    val jobs: kotlin.collections.List<kotlin.String>,

    @Json(name = "waited")
    val waited: kotlin.Boolean? = null,

    @Json(name = "timed_out")
    val timedOut: kotlin.Boolean? = null,

    @Json(name = "errors")
    val errors: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null

) {


}

