/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param callId 
 * @param status 
 * @param startedAt 
 * @param endedAt 
 * @param url 
 * @param metadata 
 */


data class CallRecording (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "callId")
    val callId: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "startedAt")
    val startedAt: java.time.OffsetDateTime? = null,

    @Json(name = "endedAt")
    val endedAt: java.time.OffsetDateTime? = null,

    @Json(name = "url")
    val url: kotlin.String? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

