/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A single cell. `value` is the JSON-serializable cell contents; interpretation is provider-specific. 
 *
 * @param row 
 * @param column 
 * @param `value` Any JSON value (string, number, boolean, null, object).
 */


data class Cell (

    @Json(name = "row")
    val row: kotlin.Int,

    @Json(name = "column")
    val column: kotlin.String,

    /* Any JSON value (string, number, boolean, null, object). */
    @Json(name = "value")
    val `value`: kotlin.Any?

) {


}

