/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientName 
 * @param redirectUris 
 * @param grantTypes 
 * @param responseTypes 
 * @param scope Space-separated scope list. Defaults to `read:*`.
 * @param tokenEndpointAuthMethod 
 * @param clientUri 
 * @param logoUri 
 * @param policyUri 
 * @param tosUri 
 */


data class ClientRegistrationRequest (

    @Json(name = "client_name")
    val clientName: kotlin.String,

    @Json(name = "redirect_uris")
    val redirectUris: kotlin.collections.List<java.net.URI>,

    @Json(name = "grant_types")
    val grantTypes: kotlin.collections.List<kotlin.String>? = arrayListOf("authorization_code","refresh_token"),

    @Json(name = "response_types")
    val responseTypes: kotlin.collections.List<kotlin.String>? = arrayListOf("code"),

    /* Space-separated scope list. Defaults to `read:*`. */
    @Json(name = "scope")
    val scope: kotlin.String? = null,

    @Json(name = "token_endpoint_auth_method")
    val tokenEndpointAuthMethod: ClientRegistrationRequest.TokenEndpointAuthMethod? = TokenEndpointAuthMethod.none,

    @Json(name = "client_uri")
    val clientUri: java.net.URI? = null,

    @Json(name = "logo_uri")
    val logoUri: java.net.URI? = null,

    @Json(name = "policy_uri")
    val policyUri: java.net.URI? = null,

    @Json(name = "tos_uri")
    val tosUri: java.net.URI? = null

) {

    /**
     * 
     *
     * Values: none,client_secret_basic,client_secret_post
     */
    @JsonClass(generateAdapter = false)
    enum class TokenEndpointAuthMethod(val value: kotlin.String) {
        @Json(name = "none") none("none"),
        @Json(name = "client_secret_basic") client_secret_basic("client_secret_basic"),
        @Json(name = "client_secret_post") client_secret_post("client_secret_post");
    }

}

