/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param success 
 * @param fileId 
 * @param manifestId 
 * @param version 
 * @param totalSize 
 * @param physicalSize 
 * @param deduplicationPct 
 * @param totalBlocks 
 * @param newBlocks 
 * @param deduplicatedBlocks 
 */


data class CommitChunkedUploadResponse (

    @Json(name = "success")
    val success: kotlin.Boolean,

    @Json(name = "fileId")
    val fileId: kotlin.String,

    @Json(name = "manifestId")
    val manifestId: kotlin.String,

    @Json(name = "version")
    val version: kotlin.Int,

    @Json(name = "totalSize")
    val totalSize: kotlin.Long,

    @Json(name = "physicalSize")
    val physicalSize: kotlin.Long? = null,

    @Json(name = "deduplicationPct")
    val deduplicationPct: kotlin.Double? = null,

    @Json(name = "totalBlocks")
    val totalBlocks: kotlin.Int? = null,

    @Json(name = "newBlocks")
    val newBlocks: kotlin.Int? = null,

    @Json(name = "deduplicatedBlocks")
    val deduplicatedBlocks: kotlin.Int? = null

) {


}

