/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Video/phone conference details. `type` is canonical (`spatio`, `meet`, `zoom`, `teams`); other provider-specific values are accepted as opaque strings. The Spatio invite email pipeline only fires for native events or events with `type: spatio`. 
 *
 * @param type 
 * @param uri 
 * @param meetingId 
 * @param passcode 
 * @param accessCode 
 * @param dialIn 
 */


data class ConferenceData (

    @Json(name = "type")
    val type: kotlin.String,

    @Json(name = "uri")
    val uri: java.net.URI,

    @Json(name = "meeting_id")
    val meetingId: kotlin.String? = null,

    @Json(name = "passcode")
    val passcode: kotlin.String? = null,

    @Json(name = "access_code")
    val accessCode: kotlin.String? = null,

    @Json(name = "dial_in")
    val dialIn: kotlin.collections.List<kotlin.String>? = null

) {


}

