/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param clientId 
 * @param clientName 
 * @param scopes 
 * @param scopeLabels 
 * @param grantedAt 
 * @param logoUri 
 * @param clientUri 
 * @param policyUri 
 * @param tosUri 
 */


data class ConnectedAppItem (

    @Json(name = "client_id")
    val clientId: kotlin.String,

    @Json(name = "client_name")
    val clientName: kotlin.String,

    @Json(name = "scopes")
    val scopes: kotlin.collections.List<kotlin.String>,

    @Json(name = "scope_labels")
    val scopeLabels: kotlin.collections.List<kotlin.String>,

    @Json(name = "granted_at")
    val grantedAt: java.time.OffsetDateTime,

    @Json(name = "logo_uri")
    val logoUri: kotlin.String? = null,

    @Json(name = "client_uri")
    val clientUri: kotlin.String? = null,

    @Json(name = "policy_uri")
    val policyUri: kotlin.String? = null,

    @Json(name = "tos_uri")
    val tosUri: kotlin.String? = null

) {


}

