/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * `GET /v1/connections/user` returns `{connections, user_id}` (the per-provider connected-account list). Schema kept open pending a normalize-to-`accounts` migration. 
 *
 * @param connections 
 * @param userId 
 * @param accounts 
 */


data class ConnectionAccountListResponse (

    @Json(name = "connections")
    val connections: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null,

    @Json(name = "user_id")
    val userId: kotlin.String? = null,

    @Json(name = "accounts")
    val accounts: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null

) {


}

