/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Atomic check+increment. Returns the updated counter on success; returns 402 on `trial_expired` and 429 on `daily_limit_exceeded` (the body in error cases is the `ApiError` envelope). 
 *
 * @param allowed 
 * @param taskCount 
 * @param dailyLimit 
 * @param trialEndsAt 
 * @param paid 
 */


data class ConsumeAgentTaskResponse (

    @Json(name = "allowed")
    val allowed: kotlin.Boolean,

    @Json(name = "task_count")
    val taskCount: kotlin.Int? = null,

    @Json(name = "daily_limit")
    val dailyLimit: kotlin.Int? = null,

    @Json(name = "trial_ends_at")
    val trialEndsAt: java.time.OffsetDateTime? = null,

    @Json(name = "paid")
    val paid: kotlin.Boolean? = null

) {


}

