/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.Contact

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param contacts 
 * @param totalResults 
 * @param updatedAt 
 */


data class ContactListResponse (

    @Json(name = "contacts")
    val contacts: kotlin.collections.List<Contact>,

    @Json(name = "total_results")
    val totalResults: kotlin.Int? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

