/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * LLM conversation persisted by the platform-service. Stored in snake_case at the wire (legacy DTO; predates the camelCase rest of the API). Treat field names as authoritative. 
 *
 * @param id 
 * @param userId 
 * @param title 
 * @param context Free-form context tag (e.g. `sidebar:sheets:entity:<id>`).
 * @param cwd 
 * @param sessionId 
 * @param pinned 
 * @param lastMessageAt 
 * @param messageCount 
 * @param isActive 
 * @param metadata 
 * @param createdAt 
 * @param updatedAt 
 */


data class Conversation (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "user_id")
    val userId: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    /* Free-form context tag (e.g. `sidebar:sheets:entity:<id>`). */
    @Json(name = "context")
    val context: kotlin.String? = null,

    @Json(name = "cwd")
    val cwd: kotlin.String? = null,

    @Json(name = "session_id")
    val sessionId: kotlin.String? = null,

    @Json(name = "pinned")
    val pinned: kotlin.Boolean? = null,

    @Json(name = "last_message_at")
    val lastMessageAt: java.time.OffsetDateTime? = null,

    @Json(name = "message_count")
    val messageCount: kotlin.Int? = null,

    @Json(name = "is_active")
    val isActive: kotlin.Boolean? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

