/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.PersonalAccessToken

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The full token (prefix + secret) is returned ONLY on creation. Store it now or you'll have to recreate; the API never returns the secret again. 
 *
 * @param token 
 * @param pat 
 */


data class CreatePATResponse (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "pat")
    val pat: PersonalAccessToken? = null

) {


}

