/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param content 
 * @param icon 
 * @param coverImage 
 * @param parentId 
 * @param properties 
 * @param accountId Optional override for the target connected account. May also be passed as a `?accountId=` query param. 
 * @param provider Optional provider id (alternative to `accountId` when only one account exists for the provider). May also be passed as a `?provider=` query param. 
 */


data class CreateNoteRequest (

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "coverImage")
    val coverImage: java.net.URI? = null,

    @Json(name = "parentId")
    val parentId: kotlin.String? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Optional override for the target connected account. May also be passed as a `?accountId=` query param.  */
    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    /* Optional provider id (alternative to `accountId` when only one account exists for the provider). May also be passed as a `?provider=` query param.  */
    @Json(name = "provider")
    val provider: kotlin.String? = null

) {


}

