/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Either `body` (preferred) or `content` (renderer parity with tasks) is required. Empty `parentCommentId`/`blockId` strings are treated as `null`. 
 *
 * @param body 
 * @param content 
 * @param parentCommentId 
 * @param blockId 
 */


data class CreateCommentRequest (

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "content")
    val content: kotlin.String? = null,

    @Json(name = "parentCommentId")
    val parentCommentId: kotlin.String? = null,

    @Json(name = "blockId")
    val blockId: kotlin.String? = null

) {


}

