/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param description 
 * @param systemPrompt 
 * @param tools 
 * @param icon 
 * @param color 
 * @param metadata 
 */


data class CreateAgentRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "systemPrompt")
    val systemPrompt: kotlin.String? = null,

    @Json(name = "tools")
    val tools: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "icon")
    val icon: kotlin.String? = null,

    @Json(name = "color")
    val color: kotlin.String? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

