/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param name 
 * @param accountId 
 * @param parentId 
 * @param workspaceId 
 * @param organizationId 
 */


data class CreateFolderRequest (

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    @Json(name = "parentId")
    val parentId: kotlin.String? = null,

    @Json(name = "workspaceId")
    val workspaceId: kotlin.String? = null,

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null

) {


}

