/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.AttachmentInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param accountId 
 * @param to 
 * @param cc 
 * @param bcc 
 * @param subject 
 * @param body 
 * @param html 
 * @param attachments 
 * @param threadId Provider thread id — set when this draft is a reply, so the sent message lands inside the parent thread. 
 * @param inReplyTo 
 * @param references 
 */


data class CreateDraftRequest (

    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    @Json(name = "to")
    val to: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "cc")
    val cc: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "bcc")
    val bcc: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "html")
    val html: kotlin.Boolean? = null,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentInput>? = null,

    /* Provider thread id — set when this draft is a reply, so the sent message lands inside the parent thread.  */
    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "inReplyTo")
    val inReplyTo: kotlin.String? = null,

    @Json(name = "references")
    val references: kotlin.collections.List<kotlin.String>? = null

) {


}

