/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.ChatMessage

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Generic single-message wrapper used by reply/forward/attach responses. `message` is the resulting `ChatMessage`. 
 *
 * @param message 
 */


data class DMMessageEnvelope (

    @Json(name = "message")
    val message: ChatMessage

) {


}

