/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Body for `POST /v1/notes/{id}/share`. With `setPassword: false`, only the public flag is flipped — any existing password is preserved. With `setPassword: true`, the supplied `password` is applied (an empty string clears it). 
 *
 * @param setPassword 
 * @param password 
 */


data class EnableShareRequest (

    @Json(name = "setPassword")
    val setPassword: kotlin.Boolean? = null,

    @Json(name = "password")
    val password: kotlin.String? = null

) {


}

