/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Generic action-execute result envelope. Tool-specific shape lives in `data`.
 *
 * @param ok 
 * @param `data` 
 * @param error 
 */


data class ExecuteActionResponse (

    @Json(name = "ok")
    val ok: kotlin.Boolean? = null,

    @Json(name = "data")
    val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

