/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Response shape when the export was uploaded to R2 (`?storage=r2`). The streaming case (`?storage=stream`, default) returns a binary `application/pdf` body and is not modeled as a JSON schema. 
 *
 * @param storage 
 * @param url 24-hour signed URL.
 * @param expiresAt 
 * @param propertySize PDF size in bytes.
 */


data class ExportPDFR2Response (

    @Json(name = "storage")
    val storage: ExportPDFR2Response.Storage,

    /* 24-hour signed URL. */
    @Json(name = "url")
    val url: java.net.URI,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime,

    /* PDF size in bytes. */
    @Json(name = "size")
    val propertySize: kotlin.Int

) {

    /**
     * 
     *
     * Values: r2
     */
    @JsonClass(generateAdapter = false)
    enum class Storage(val value: kotlin.String) {
        @Json(name = "r2") r2("r2");
    }

}

