/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.AccountStatus
import app.spatio.client.models.Folder
import app.spatio.client.models.SpatioFile

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Aggregated `{files, folders, accounts}` envelope used by the renderer's file-browser. Calls `ListFiles` and `ListFolders` in parallel and merges the results — saves a round-trip when the UI shows both side-by-side. 
 *
 * @param total 
 * @param hasMore 
 * @param files 
 * @param folders 
 * @param accounts 
 * @param nextOffset 
 */


data class FilesAndFoldersResponse (

    @Json(name = "total")
    val total: kotlin.Int,

    @Json(name = "hasMore")
    val hasMore: kotlin.Boolean,

    @Json(name = "files")
    val files: kotlin.collections.List<SpatioFile>? = null,

    @Json(name = "folders")
    val folders: kotlin.collections.List<Folder>? = null,

    @Json(name = "accounts")
    val accounts: kotlin.collections.List<AccountStatus>? = null,

    @Json(name = "nextOffset")
    val nextOffset: kotlin.Int? = null

) {


}

