/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param sessionId 
 * @param blocksToUpload 
 * @param blocksAlreadyExist Blocks the platform already has and the client can skip (content-addressed deduplication). 
 * @param deduplicationPct 
 * @param estimatedUploadSize 
 */


data class InitChunkedUploadResponse (

    @Json(name = "sessionId")
    val sessionId: kotlin.String,

    @Json(name = "blocksToUpload")
    val blocksToUpload: kotlin.collections.List<kotlin.String>,

    /* Blocks the platform already has and the client can skip (content-addressed deduplication).  */
    @Json(name = "blocksAlreadyExist")
    val blocksAlreadyExist: kotlin.collections.List<kotlin.String>,

    @Json(name = "deduplicationPct")
    val deduplicationPct: kotlin.Double,

    @Json(name = "estimatedUploadSize")
    val estimatedUploadSize: kotlin.Long

) {


}

