/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.Draft

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param drafts 
 * @param total 
 * @param provider 
 * @param nextPageToken 
 */


data class ListDraftsResponse (

    @Json(name = "drafts")
    val drafts: kotlin.collections.List<Draft>,

    @Json(name = "total")
    val total: kotlin.Int,

    @Json(name = "provider")
    val provider: kotlin.String,

    @Json(name = "nextPageToken")
    val nextPageToken: kotlin.String? = null

) {


}

