/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A markdown note. Notes belong to exactly one connected account (`accountId` + `provider`). The native provider stores notes in the Spatio database; external providers (Notion, Google Keep, etc.) store them upstream and round-trip through Spatio. 
 *
 * @param id Stable provider id for the note.
 * @param title 
 * @param content Markdown body. The block tree at `/v1/notes/{id}/blocks` is the canonical structured representation; `content` is a flattened markdown view kept for clients that don't render blocks. 
 * @param archived 
 * @param createdAt 
 * @param updatedAt 
 * @param provider Registered provider id (e.g. `native-notes`).
 * @param accountId Connected-account row this note belongs to.
 * @param ownerUserId User id of the note's owner. Surfaced so the renderer can show \"Shared with you\" when `ownerUserId` differs from the viewer's id. Empty for non-native providers. 
 * @param icon Emoji or short string used as the note's icon.
 * @param coverImage URL of the note's cover image.
 * @param parentId Parent note id when notes are nested.
 * @param properties Free-form provider-specific properties (tags, etc.).
 * @param lastEditedBy User id of the most recent editor.
 */


data class Note (

    /* Stable provider id for the note. */
    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    /* Markdown body. The block tree at `/v1/notes/{id}/blocks` is the canonical structured representation; `content` is a flattened markdown view kept for clients that don't render blocks.  */
    @Json(name = "content")
    val content: kotlin.String,

    @Json(name = "archived")
    val archived: kotlin.Boolean,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Registered provider id (e.g. `native-notes`). */
    @Json(name = "provider")
    val provider: kotlin.String? = null,

    /* Connected-account row this note belongs to. */
    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    /* User id of the note's owner. Surfaced so the renderer can show \"Shared with you\" when `ownerUserId` differs from the viewer's id. Empty for non-native providers.  */
    @Json(name = "ownerUserId")
    val ownerUserId: kotlin.String? = null,

    /* Emoji or short string used as the note's icon. */
    @Json(name = "icon")
    val icon: kotlin.String? = null,

    /* URL of the note's cover image. */
    @Json(name = "coverImage")
    val coverImage: java.net.URI? = null,

    /* Parent note id when notes are nested. */
    @Json(name = "parentId")
    val parentId: kotlin.String? = null,

    /* Free-form provider-specific properties (tags, etc.). */
    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* User id of the most recent editor. */
    @Json(name = "lastEditedBy")
    val lastEditedBy: kotlin.String? = null

) {


}

