/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.OrganizationMemberInvitedBy

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param email 
 * @param role 
 * @param createdAt 
 * @param organizationId 
 * @param token Opaque invitation token (omitted on list responses).
 * @param expiresAt 
 * @param acceptedAt 
 * @param revokedAt 
 * @param invitedBy 
 * @param status 
 */


data class OrganizationInvitation (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "role")
    val role: kotlin.String,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    /* Opaque invitation token (omitted on list responses). */
    @Json(name = "token")
    val token: kotlin.String? = null,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null,

    @Json(name = "acceptedAt")
    val acceptedAt: java.time.OffsetDateTime? = null,

    @Json(name = "revokedAt")
    val revokedAt: java.time.OffsetDateTime? = null,

    @Json(name = "invitedBy")
    val invitedBy: OrganizationMemberInvitedBy? = null,

    @Json(name = "status")
    val status: OrganizationInvitation.Status? = null

) {

    /**
     * 
     *
     * Values: pending,accepted,revoked,expired
     */
    @JsonClass(generateAdapter = false)
    enum class Status(val value: kotlin.String) {
        @Json(name = "pending") pending("pending"),
        @Json(name = "accepted") accepted("accepted"),
        @Json(name = "revoked") revoked("revoked"),
        @Json(name = "expired") expired("expired");
    }

}

