/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Inviter info. Returns either a bare user id (`string`) on legacy paths, or an object envelope `{id, email, name, ...}` on enriched responses. Treat as opaque. 
 *
 */


class OrganizationMemberInvitedBy (

) {


}

