/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param kind 
 * @param workspaceId 
 * @param title 
 * @param body 
 * @param payload 
 * @param expiresAt 
 */


data class ProposeRecommendationRequest (

    @Json(name = "kind")
    val kind: kotlin.String,

    @Json(name = "workspaceId")
    val workspaceId: kotlin.String? = null,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "payload")
    val payload: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "expiresAt")
    val expiresAt: java.time.OffsetDateTime? = null

) {


}

