/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param routineId 
 * @param status 
 * @param progress 
 * @param metadata 
 * @param startedAt 
 * @param completedAt 
 */


data class RoutineRun (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "routineId")
    val routineId: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "progress")
    val progress: kotlin.Int? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "startedAt")
    val startedAt: java.time.OffsetDateTime? = null,

    @Json(name = "completedAt")
    val completedAt: java.time.OffsetDateTime? = null

) {


}

