/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param success 
 * @param messageId 
 * @param provider 
 * @param threadId 
 * @param error 
 */


data class SendEmailResponse (

    @Json(name = "success")
    val success: kotlin.Boolean,

    @Json(name = "messageId")
    val messageId: kotlin.String,

    @Json(name = "provider")
    val provider: kotlin.String,

    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    @Json(name = "error")
    val error: kotlin.String? = null

) {


}

