/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param channel Channel or DM id (provider-scoped).
 * @param text 
 * @param accountId 
 * @param threadId 
 * @param blocks Provider-specific rich-message blocks.
 */


data class SendChatMessageRequest (

    /* Channel or DM id (provider-scoped). */
    @Json(name = "channel")
    val channel: kotlin.String,

    @Json(name = "text")
    val text: kotlin.String,

    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    @Json(name = "threadId")
    val threadId: kotlin.String? = null,

    /* Provider-specific rich-message blocks. */
    @Json(name = "blocks")
    val blocks: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null

) {


}

