/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.SignInMethodsProvidersInner

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param email 
 * @param hasPassword 
 * @param providers 
 */


data class SignInMethods (

    @Json(name = "email")
    val email: kotlin.String,

    @Json(name = "hasPassword")
    val hasPassword: kotlin.Boolean,

    @Json(name = "providers")
    val providers: kotlin.collections.List<SignInMethodsProvidersInner>? = null

) {


}

