/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * One canvas object on a slide — text box, shape, image, etc. `content` is renderer-specific JSON (e.g. fabric.js properties: text, fill, fontSize, src). Identified by a stable `id` so MCP / agent operations stay idempotent across retries. 
 *
 * @param id 
 * @param slideId 
 * @param elementType Free-form type id (`text`, `image`, `shape`, etc.).
 * @param content 
 * @param x 
 * @param y 
 * @param width 
 * @param height 
 * @param rotation Degrees.
 * @param zIndex 
 * @param createdAt 
 * @param updatedAt 
 */


data class SlideElement (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "slideId")
    val slideId: kotlin.String,

    /* Free-form type id (`text`, `image`, `shape`, etc.). */
    @Json(name = "elementType")
    val elementType: kotlin.String,

    @Json(name = "content")
    val content: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "x")
    val x: kotlin.Double,

    @Json(name = "y")
    val y: kotlin.Double,

    @Json(name = "width")
    val width: kotlin.Double,

    @Json(name = "height")
    val height: kotlin.Double,

    /* Degrees. */
    @Json(name = "rotation")
    val rotation: kotlin.Double,

    @Json(name = "zIndex")
    val zIndex: kotlin.Int,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime

) {


}

