/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param title 
 * @param status 
 * @param hostUserId 
 * @param workspaceId 
 * @param roomId 
 * @param participants 
 * @param metadata 
 * @param startedAt 
 * @param endedAt 
 * @param createdAt 
 */


data class SpatioCall (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "hostUserId")
    val hostUserId: kotlin.String? = null,

    @Json(name = "workspaceId")
    val workspaceId: kotlin.String? = null,

    @Json(name = "roomId")
    val roomId: kotlin.String? = null,

    @Json(name = "participants")
    val participants: kotlin.collections.List<kotlin.collections.Map<kotlin.String, kotlin.Any>>? = null,

    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "startedAt")
    val startedAt: java.time.OffsetDateTime? = null,

    @Json(name = "endedAt")
    val endedAt: java.time.OffsetDateTime? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null

) {


}

