/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A to-do / reminder / issue. Tasks belong to one connected account (`accountId` + `provider`). Native tasks store in Spatio's DB; external providers (Linear, GitHub Issues, Todoist, etc.) round-trip through Spatio. 
 *
 * @param id 
 * @param title 
 * @param completed 
 * @param priority Priority bucket. Canonical values (mapped from a 0–4 integer): `none`, `low`, `medium`, `high`, `urgent`. 
 * @param createdAt 
 * @param updatedAt 
 * @param provider Registered provider id (e.g. `native-tasks`, `linear`).
 * @param accountId 
 * @param ownerUserId 
 * @param description 
 * @param status Free-form status string. Canonical values across most providers: `todo`, `in_progress`, `in_review`, `backlog`, `done`. The platform falls back to `done` when `completed` is true and `status` is empty, else `todo`. 
 * @param dueDate 
 * @param labels 
 * @param tags 
 * @param assigneeId 
 * @param completedAt 
 * @param parentTaskId Parent task id when this is a subtask.
 * @param metadata Provider-specific extras.
 * @param type Discriminator. Canonical values: `todo`, `reminder`, `issue`. Empty defaults to `todo`. 
 * @param sourcePlatform When this task was auto-generated from another artifact (e.g. a calendar event reminder), the platform id of that artifact. 
 * @param sourceId Source artifact id paired with `sourcePlatform`.
 */


data class Task (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "title")
    val title: kotlin.String,

    @Json(name = "completed")
    val completed: kotlin.Boolean,

    /* Priority bucket. Canonical values (mapped from a 0–4 integer): `none`, `low`, `medium`, `high`, `urgent`.  */
    @Json(name = "priority")
    val priority: Task.Priority,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime,

    /* Registered provider id (e.g. `native-tasks`, `linear`). */
    @Json(name = "provider")
    val provider: kotlin.String? = null,

    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    @Json(name = "ownerUserId")
    val ownerUserId: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    /* Free-form status string. Canonical values across most providers: `todo`, `in_progress`, `in_review`, `backlog`, `done`. The platform falls back to `done` when `completed` is true and `status` is empty, else `todo`.  */
    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "dueDate")
    val dueDate: java.time.OffsetDateTime? = null,

    @Json(name = "labels")
    val labels: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "assigneeId")
    val assigneeId: kotlin.String? = null,

    @Json(name = "completedAt")
    val completedAt: java.time.OffsetDateTime? = null,

    /* Parent task id when this is a subtask. */
    @Json(name = "parentTaskId")
    val parentTaskId: kotlin.String? = null,

    /* Provider-specific extras. */
    @Json(name = "metadata")
    val metadata: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    /* Discriminator. Canonical values: `todo`, `reminder`, `issue`. Empty defaults to `todo`.  */
    @Json(name = "type")
    val type: kotlin.String? = null,

    /* When this task was auto-generated from another artifact (e.g. a calendar event reminder), the platform id of that artifact.  */
    @Json(name = "sourcePlatform")
    val sourcePlatform: kotlin.String? = null,

    /* Source artifact id paired with `sourcePlatform`. */
    @Json(name = "sourceId")
    val sourceId: kotlin.String? = null

) {

    /**
     * Priority bucket. Canonical values (mapped from a 0–4 integer): `none`, `low`, `medium`, `high`, `urgent`. 
     *
     * Values: none,low,medium,high,urgent
     */
    @JsonClass(generateAdapter = false)
    enum class Priority(val value: kotlin.String) {
        @Json(name = "none") none("none"),
        @Json(name = "low") low("low"),
        @Json(name = "medium") medium("medium"),
        @Json(name = "high") high("high"),
        @Json(name = "urgent") urgent("urgent");
    }

}

