/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.AttachmentInput

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Partial update — every field optional.
 *
 * @param accountId 
 * @param to 
 * @param cc 
 * @param bcc 
 * @param subject 
 * @param body 
 * @param html 
 * @param attachments 
 */


data class UpdateDraftRequest (

    @Json(name = "accountId")
    val accountId: kotlin.String? = null,

    @Json(name = "to")
    val to: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "cc")
    val cc: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "bcc")
    val bcc: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "subject")
    val subject: kotlin.String? = null,

    @Json(name = "body")
    val body: kotlin.String? = null,

    @Json(name = "html")
    val html: kotlin.Boolean? = null,

    @Json(name = "attachments")
    val attachments: kotlin.collections.List<AttachmentInput>? = null

) {


}

