/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Partial update — every field is optional. `dueDate` and `parentTaskId` are nullable: send `null` to clear, omit to leave untouched, send a value to set. 
 *
 * @param title 
 * @param description 
 * @param status 
 * @param dueDate 
 * @param priority 
 * @param labels 
 * @param tags 
 * @param assigneeId 
 * @param parentTaskId 
 */


data class UpdateTaskRequest (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "status")
    val status: kotlin.String? = null,

    @Json(name = "dueDate")
    val dueDate: java.time.OffsetDateTime? = null,

    @Json(name = "priority")
    val priority: UpdateTaskRequest.Priority? = null,

    @Json(name = "labels")
    val labels: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    @Json(name = "assigneeId")
    val assigneeId: kotlin.String? = null,

    @Json(name = "parentTaskId")
    val parentTaskId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: none,low,medium,high,urgent
     */
    @JsonClass(generateAdapter = false)
    enum class Priority(val value: kotlin.String) {
        @Json(name = "none") none("none"),
        @Json(name = "low") low("low"),
        @Json(name = "medium") medium("medium"),
        @Json(name = "high") high("high"),
        @Json(name = "urgent") urgent("urgent");
    }

}

