/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param title 
 * @param context 
 * @param cwd 
 * @param sessionId 
 * @param pinned 
 */


data class UpdateConversationRequest (

    @Json(name = "title")
    val title: kotlin.String? = null,

    @Json(name = "context")
    val context: kotlin.String? = null,

    @Json(name = "cwd")
    val cwd: kotlin.String? = null,

    @Json(name = "session_id")
    val sessionId: kotlin.String? = null,

    @Json(name = "pinned")
    val pinned: kotlin.Boolean? = null

) {


}

