/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Sparse update. `updates` is a free-form map of fields to change; only keys present are applied. The server-side capability gate rejects fields that the underlying provider doesn't support. 
 *
 * @param accountId 
 * @param updates 
 * @param sendUpdates 
 */


data class UpdateEventRequest (

    @Json(name = "account_id")
    val accountId: kotlin.String,

    @Json(name = "updates")
    val updates: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @Json(name = "send_updates")
    val sendUpdates: UpdateEventRequest.SendUpdates? = null

) {

    /**
     * 
     *
     * Values: all,externalOnly,none
     */
    @JsonClass(generateAdapter = false)
    enum class SendUpdates(val value: kotlin.String) {
        @Json(name = "all") all("all"),
        @Json(name = "externalOnly") externalOnly("externalOnly"),
        @Json(name = "none") none("none");
    }

}

