/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.BlockContent

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Partial update — only fields present in the body are touched.
 *
 * @param content 
 * @param properties 
 * @param archived 
 */


data class UpdateBlockRequest (

    @Json(name = "content")
    val content: BlockContent? = null,

    @Json(name = "properties")
    val properties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "archived")
    val archived: kotlin.Boolean? = null

) {


}

