/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param id 
 * @param role 
 * @param joinedAt 
 * @param email 
 * @param name 
 * @param avatar 
 * @param user 
 */


data class WorkspaceMember (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "role")
    val role: WorkspaceMember.Role,

    @Json(name = "joinedAt")
    val joinedAt: java.time.OffsetDateTime,

    @Json(name = "email")
    val email: kotlin.String? = null,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "avatar")
    val avatar: java.net.URI? = null,

    @Json(name = "user")
    val user: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {

    /**
     * 
     *
     * Values: owner,admin,member,guest
     */
    @JsonClass(generateAdapter = false)
    enum class Role(val value: kotlin.String) {
        @Json(name = "owner") owner("owner"),
        @Json(name = "admin") admin("admin"),
        @Json(name = "member") member("member"),
        @Json(name = "guest") guest("guest");
    }

}

