/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.models

import app.spatio.client.models.WorkspaceOrganization

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * A workspace within an organization. Returned in list responses (`GET /v1/workspaces`, `GET /v1/organizations/{id}/workspaces`) and the single-get response (`GET /v1/workspaces/{id}`, wrapped in `{workspace: ...}`).  `settings` shape varies by endpoint — sometimes a JSON object, sometimes a JSON-encoded string. Treat as opaque. 
 *
 * @param id 
 * @param name 
 * @param slug 
 * @param description 
 * @param logoUrl 
 * @param organizationId 
 * @param organization 
 * @param role The caller's role in this workspace (`owner`, `admin`, `member`, `guest`).
 * @param settings Per-workspace settings. Currently emitted as either an object (`{language, timezone, ...}`) on `GET /v1/workspaces/{id}` or a JSON-encoded string on `GET /v1/organizations/{id}/workspaces`. Treat as opaque and parse defensively. 
 * @param isDefault 
 * @param memberCount 
 * @param billingTier 
 * @param createdAt 
 * @param updatedAt 
 */


data class Workspace (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "slug")
    val slug: kotlin.String,

    @Json(name = "description")
    val description: kotlin.String? = null,

    @Json(name = "logoUrl")
    val logoUrl: kotlin.String? = null,

    @Json(name = "organizationId")
    val organizationId: kotlin.String? = null,

    @Json(name = "organization")
    val organization: WorkspaceOrganization? = null,

    /* The caller's role in this workspace (`owner`, `admin`, `member`, `guest`). */
    @Json(name = "role")
    val role: kotlin.String? = null,

    /* Per-workspace settings. Currently emitted as either an object (`{language, timezone, ...}`) on `GET /v1/workspaces/{id}` or a JSON-encoded string on `GET /v1/organizations/{id}/workspaces`. Treat as opaque and parse defensively.  */
    @Json(name = "settings")
    val settings: kotlin.Any? = null,

    @Json(name = "isDefault")
    val isDefault: kotlin.Boolean? = null,

    @Json(name = "memberCount")
    val memberCount: kotlin.Int? = null,

    @Json(name = "billingTier")
    val billingTier: kotlin.String? = null,

    @Json(name = "createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @Json(name = "updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

) {


}

