/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import app.spatio.client.models.ActionDescriptor
import app.spatio.client.models.ApiError
import app.spatio.client.models.CoreAction
import app.spatio.client.models.CoreActionListResponse
import app.spatio.client.models.ExecuteActionRequest
import app.spatio.client.models.ExecuteActionResponse

import com.squareup.moshi.Json

import app.spatio.client.infrastructure.ApiClient
import app.spatio.client.infrastructure.ApiResponse
import app.spatio.client.infrastructure.ClientException
import app.spatio.client.infrastructure.ClientError
import app.spatio.client.infrastructure.ServerException
import app.spatio.client.infrastructure.ServerError
import app.spatio.client.infrastructure.MultiValueMap
import app.spatio.client.infrastructure.PartConfig
import app.spatio.client.infrastructure.RequestConfig
import app.spatio.client.infrastructure.RequestMethod
import app.spatio.client.infrastructure.ResponseType
import app.spatio.client.infrastructure.Success
import app.spatio.client.infrastructure.toMultiValue

open class ActionsApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.spatio.app")
        }
    }

    /**
     * POST /v1/actions/execute
     * Renderer-side execute alias. The canonical endpoint is &#x60;POST /v1/agent/actions/execute&#x60;; this path delegates to the same handler. 
     * 
     * @param executeActionRequest 
     * @return ExecuteActionResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun executeAction(executeActionRequest: ExecuteActionRequest) : ExecuteActionResponse {
        val localVarResponse = executeActionWithHttpInfo(executeActionRequest = executeActionRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as ExecuteActionResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/actions/execute
     * Renderer-side execute alias. The canonical endpoint is &#x60;POST /v1/agent/actions/execute&#x60;; this path delegates to the same handler. 
     * 
     * @param executeActionRequest 
     * @return ApiResponse<ExecuteActionResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun executeActionWithHttpInfo(executeActionRequest: ExecuteActionRequest) : ApiResponse<ExecuteActionResponse?> {
        val localVariableConfig = executeActionRequestConfig(executeActionRequest = executeActionRequest)

        return request<ExecuteActionRequest, ExecuteActionResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation executeAction
     *
     * @param executeActionRequest 
     * @return RequestConfig
     */
    fun executeActionRequestConfig(executeActionRequest: ExecuteActionRequest) : RequestConfig<ExecuteActionRequest> {
        val localVariableBody = executeActionRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/actions/execute",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/actions/core/{id}
     * Fetch a single core action by id.
     * 
     * @param id 
     * @return CoreAction
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getCoreAction(id: kotlin.String) : CoreAction {
        val localVarResponse = getCoreActionWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CoreAction
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/actions/core/{id}
     * Fetch a single core action by id.
     * 
     * @param id 
     * @return ApiResponse<CoreAction?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getCoreActionWithHttpInfo(id: kotlin.String) : ApiResponse<CoreAction?> {
        val localVariableConfig = getCoreActionRequestConfig(id = id)

        return request<Unit, CoreAction>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getCoreAction
     *
     * @param id 
     * @return RequestConfig
     */
    fun getCoreActionRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/actions/core/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/actions/available
     * List every action the agent platform exposes.
     * 
     * @return kotlin.collections.List<ActionDescriptor>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAvailableActions() : kotlin.collections.List<ActionDescriptor> {
        val localVarResponse = listAvailableActionsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ActionDescriptor>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/actions/available
     * List every action the agent platform exposes.
     * 
     * @return ApiResponse<kotlin.collections.List<ActionDescriptor>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listAvailableActionsWithHttpInfo() : ApiResponse<kotlin.collections.List<ActionDescriptor>?> {
        val localVariableConfig = listAvailableActionsRequestConfig()

        return request<Unit, kotlin.collections.List<ActionDescriptor>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAvailableActions
     *
     * @return RequestConfig
     */
    fun listAvailableActionsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/actions/available",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/actions/core
     * List renderer-curated \&quot;core actions\&quot; (command-palette + keybindings backing).
     * 
     * @return CoreActionListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listCoreActions() : CoreActionListResponse {
        val localVarResponse = listCoreActionsWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CoreActionListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/actions/core
     * List renderer-curated \&quot;core actions\&quot; (command-palette + keybindings backing).
     * 
     * @return ApiResponse<CoreActionListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listCoreActionsWithHttpInfo() : ApiResponse<CoreActionListResponse?> {
        val localVariableConfig = listCoreActionsRequestConfig()

        return request<Unit, CoreActionListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCoreActions
     *
     * @return RequestConfig
     */
    fun listCoreActionsRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/actions/core",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/actions/core/platform/{platform}
     * Core actions filtered to one platform.
     * 
     * @param platform 
     * @return CoreActionListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listCoreActionsByPlatform(platform: kotlin.String) : CoreActionListResponse {
        val localVarResponse = listCoreActionsByPlatformWithHttpInfo(platform = platform)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CoreActionListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/actions/core/platform/{platform}
     * Core actions filtered to one platform.
     * 
     * @param platform 
     * @return ApiResponse<CoreActionListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listCoreActionsByPlatformWithHttpInfo(platform: kotlin.String) : ApiResponse<CoreActionListResponse?> {
        val localVariableConfig = listCoreActionsByPlatformRequestConfig(platform = platform)

        return request<Unit, CoreActionListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listCoreActionsByPlatform
     *
     * @param platform 
     * @return RequestConfig
     */
    fun listCoreActionsByPlatformRequestConfig(platform: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/actions/core/platform/{platform}".replace("{"+"platform"+"}", encodeURIComponent(platform.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/actions/platform/{platform}
     * List actions tagged for a specific platform (notes, mail, ...).
     * 
     * @param platform 
     * @return kotlin.collections.List<ActionDescriptor>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listPlatformActions(platform: kotlin.String) : kotlin.collections.List<ActionDescriptor> {
        val localVarResponse = listPlatformActionsWithHttpInfo(platform = platform)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.List<ActionDescriptor>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/actions/platform/{platform}
     * List actions tagged for a specific platform (notes, mail, ...).
     * 
     * @param platform 
     * @return ApiResponse<kotlin.collections.List<ActionDescriptor>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listPlatformActionsWithHttpInfo(platform: kotlin.String) : ApiResponse<kotlin.collections.List<ActionDescriptor>?> {
        val localVariableConfig = listPlatformActionsRequestConfig(platform = platform)

        return request<Unit, kotlin.collections.List<ActionDescriptor>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPlatformActions
     *
     * @param platform 
     * @return RequestConfig
     */
    fun listPlatformActionsRequestConfig(platform: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/actions/platform/{platform}".replace("{"+"platform"+"}", encodeURIComponent(platform.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
