/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package app.spatio.client.apis

import java.io.IOException
import okhttp3.Call
import okhttp3.HttpUrl

import app.spatio.client.models.ApiError
import app.spatio.client.models.CreatePATRequest
import app.spatio.client.models.CreatePATResponse
import app.spatio.client.models.PATListResponse
import app.spatio.client.models.PATScopesResponse
import app.spatio.client.models.PersonalAccessToken
import app.spatio.client.models.UpdatePATRequest

import com.squareup.moshi.Json

import app.spatio.client.infrastructure.ApiClient
import app.spatio.client.infrastructure.ApiResponse
import app.spatio.client.infrastructure.ClientException
import app.spatio.client.infrastructure.ClientError
import app.spatio.client.infrastructure.ServerException
import app.spatio.client.infrastructure.ServerError
import app.spatio.client.infrastructure.MultiValueMap
import app.spatio.client.infrastructure.PartConfig
import app.spatio.client.infrastructure.RequestConfig
import app.spatio.client.infrastructure.RequestMethod
import app.spatio.client.infrastructure.ResponseType
import app.spatio.client.infrastructure.Success
import app.spatio.client.infrastructure.toMultiValue

open class PersonalAccessTokensApi(basePath: kotlin.String = defaultBasePath, client: Call.Factory = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.BASE_URL_KEY, "https://api.spatio.app")
        }
    }

    /**
     * POST /v1/tokens
     * Create a new PAT. The full token is returned only once on creation; the API never reveals the secret again. 
     * 
     * @param createPATRequest 
     * @return CreatePATResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun createPersonalAccessToken(createPATRequest: CreatePATRequest) : CreatePATResponse {
        val localVarResponse = createPersonalAccessTokenWithHttpInfo(createPATRequest = createPATRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as CreatePATResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/tokens
     * Create a new PAT. The full token is returned only once on creation; the API never reveals the secret again. 
     * 
     * @param createPATRequest 
     * @return ApiResponse<CreatePATResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun createPersonalAccessTokenWithHttpInfo(createPATRequest: CreatePATRequest) : ApiResponse<CreatePATResponse?> {
        val localVariableConfig = createPersonalAccessTokenRequestConfig(createPATRequest = createPATRequest)

        return request<CreatePATRequest, CreatePATResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation createPersonalAccessToken
     *
     * @param createPATRequest 
     * @return RequestConfig
     */
    fun createPersonalAccessTokenRequestConfig(createPATRequest: CreatePATRequest) : RequestConfig<CreatePATRequest> {
        val localVariableBody = createPATRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/tokens",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/tokens/scopes
     * List the scope strings PATs can be issued with.
     * 
     * @return PATScopesResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listAvailablePATScopes() : PATScopesResponse {
        val localVarResponse = listAvailablePATScopesWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PATScopesResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/tokens/scopes
     * List the scope strings PATs can be issued with.
     * 
     * @return ApiResponse<PATScopesResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listAvailablePATScopesWithHttpInfo() : ApiResponse<PATScopesResponse?> {
        val localVariableConfig = listAvailablePATScopesRequestConfig()

        return request<Unit, PATScopesResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listAvailablePATScopes
     *
     * @return RequestConfig
     */
    fun listAvailablePATScopesRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/tokens/scopes",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/tokens
     * List the caller&#39;s personal access tokens (with available scopes).
     * 
     * @return PATListResponse
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun listPersonalAccessTokens() : PATListResponse {
        val localVarResponse = listPersonalAccessTokensWithHttpInfo()

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PATListResponse
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/tokens
     * List the caller&#39;s personal access tokens (with available scopes).
     * 
     * @return ApiResponse<PATListResponse?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun listPersonalAccessTokensWithHttpInfo() : ApiResponse<PATListResponse?> {
        val localVariableConfig = listPersonalAccessTokensRequestConfig()

        return request<Unit, PATListResponse>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation listPersonalAccessTokens
     *
     * @return RequestConfig
     */
    fun listPersonalAccessTokensRequestConfig() : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/tokens",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/tokens/{id}
     * Revoke a PAT.
     * 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun revokePersonalAccessToken(id: kotlin.String) : Unit {
        val localVarResponse = revokePersonalAccessTokenWithHttpInfo(id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/tokens/{id}
     * Revoke a PAT.
     * 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun revokePersonalAccessTokenWithHttpInfo(id: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = revokePersonalAccessTokenRequestConfig(id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation revokePersonalAccessToken
     *
     * @param id 
     * @return RequestConfig
     */
    fun revokePersonalAccessTokenRequestConfig(id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/tokens/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/tokens/{id}
     * Rename or re-describe a PAT (scopes are immutable).
     * 
     * @param id 
     * @param updatePATRequest 
     * @return PersonalAccessToken
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun updatePersonalAccessToken(id: kotlin.String, updatePATRequest: UpdatePATRequest) : PersonalAccessToken {
        val localVarResponse = updatePersonalAccessTokenWithHttpInfo(id = id, updatePATRequest = updatePATRequest)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as PersonalAccessToken
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/tokens/{id}
     * Rename or re-describe a PAT (scopes are immutable).
     * 
     * @param id 
     * @param updatePATRequest 
     * @return ApiResponse<PersonalAccessToken?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun updatePersonalAccessTokenWithHttpInfo(id: kotlin.String, updatePATRequest: UpdatePATRequest) : ApiResponse<PersonalAccessToken?> {
        val localVariableConfig = updatePersonalAccessTokenRequestConfig(id = id, updatePATRequest = updatePATRequest)

        return request<UpdatePATRequest, PersonalAccessToken>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation updatePersonalAccessToken
     *
     * @param id 
     * @param updatePATRequest 
     * @return RequestConfig
     */
    fun updatePersonalAccessTokenRequestConfig(id: kotlin.String, updatePATRequest: UpdatePATRequest) : RequestConfig<UpdatePATRequest> {
        val localVariableBody = updatePATRequest
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/tokens/{id}".replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * POST /v1/organizations/{org}/workspaces/{workspace}/tokens
     * 
     * 
     * @param org 
     * @param workspace 
     * @param requestBody 
     * @return kotlin.collections.Map<kotlin.String, kotlin.Any>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun workspaceCreatePAT(org: kotlin.String, workspace: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : kotlin.collections.Map<kotlin.String, kotlin.Any> {
        val localVarResponse = workspaceCreatePATWithHttpInfo(org = org, workspace = workspace, requestBody = requestBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlin.Any>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * POST /v1/organizations/{org}/workspaces/{workspace}/tokens
     * 
     * 
     * @param org 
     * @param workspace 
     * @param requestBody 
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun workspaceCreatePATWithHttpInfo(org: kotlin.String, workspace: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?> {
        val localVariableConfig = workspaceCreatePATRequestConfig(org = org, workspace = workspace, requestBody = requestBody)

        return request<kotlin.collections.Map<kotlin.String, kotlin.Any>, kotlin.collections.Map<kotlin.String, kotlin.Any>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation workspaceCreatePAT
     *
     * @param org 
     * @param workspace 
     * @param requestBody 
     * @return RequestConfig
     */
    fun workspaceCreatePATRequestConfig(org: kotlin.String, workspace: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : RequestConfig<kotlin.collections.Map<kotlin.String, kotlin.Any>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.POST,
            path = "/v1/organizations/{org}/workspaces/{workspace}/tokens".replace("{"+"org"+"}", encodeURIComponent(org.toString())).replace("{"+"workspace"+"}", encodeURIComponent(workspace.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * GET /v1/organizations/{org}/workspaces/{workspace}/tokens
     * 
     * 
     * @param org 
     * @param workspace 
     * @return kotlin.collections.Map<kotlin.String, kotlin.Any>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun workspaceListPATs(org: kotlin.String, workspace: kotlin.String) : kotlin.collections.Map<kotlin.String, kotlin.Any> {
        val localVarResponse = workspaceListPATsWithHttpInfo(org = org, workspace = workspace)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlin.Any>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * GET /v1/organizations/{org}/workspaces/{workspace}/tokens
     * 
     * 
     * @param org 
     * @param workspace 
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun workspaceListPATsWithHttpInfo(org: kotlin.String, workspace: kotlin.String) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?> {
        val localVariableConfig = workspaceListPATsRequestConfig(org = org, workspace = workspace)

        return request<Unit, kotlin.collections.Map<kotlin.String, kotlin.Any>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation workspaceListPATs
     *
     * @param org 
     * @param workspace 
     * @return RequestConfig
     */
    fun workspaceListPATsRequestConfig(org: kotlin.String, workspace: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/organizations/{org}/workspaces/{workspace}/tokens".replace("{"+"org"+"}", encodeURIComponent(org.toString())).replace("{"+"workspace"+"}", encodeURIComponent(workspace.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * DELETE /v1/organizations/{org}/workspaces/{workspace}/tokens/{id}
     * 
     * 
     * @param org 
     * @param workspace 
     * @param id 
     * @return void
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun workspaceRevokePAT(org: kotlin.String, workspace: kotlin.String, id: kotlin.String) : Unit {
        val localVarResponse = workspaceRevokePATWithHttpInfo(org = org, workspace = workspace, id = id)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * DELETE /v1/organizations/{org}/workspaces/{workspace}/tokens/{id}
     * 
     * 
     * @param org 
     * @param workspace 
     * @param id 
     * @return ApiResponse<Unit?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Throws(IllegalStateException::class, IOException::class)
    fun workspaceRevokePATWithHttpInfo(org: kotlin.String, workspace: kotlin.String, id: kotlin.String) : ApiResponse<Unit?> {
        val localVariableConfig = workspaceRevokePATRequestConfig(org = org, workspace = workspace, id = id)

        return request<Unit, Unit>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation workspaceRevokePAT
     *
     * @param org 
     * @param workspace 
     * @param id 
     * @return RequestConfig
     */
    fun workspaceRevokePATRequestConfig(org: kotlin.String, workspace: kotlin.String, id: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.DELETE,
            path = "/v1/organizations/{org}/workspaces/{workspace}/tokens/{id}".replace("{"+"org"+"}", encodeURIComponent(org.toString())).replace("{"+"workspace"+"}", encodeURIComponent(workspace.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }

    /**
     * PATCH /v1/organizations/{org}/workspaces/{workspace}/tokens/{id}
     * 
     * 
     * @param org 
     * @param workspace 
     * @param id 
     * @param requestBody 
     * @return kotlin.collections.Map<kotlin.String, kotlin.Any>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun workspaceUpdatePAT(org: kotlin.String, workspace: kotlin.String, id: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : kotlin.collections.Map<kotlin.String, kotlin.Any> {
        val localVarResponse = workspaceUpdatePATWithHttpInfo(org = org, workspace = workspace, id = id, requestBody = requestBody)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as kotlin.collections.Map<kotlin.String, kotlin.Any>
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * PATCH /v1/organizations/{org}/workspaces/{workspace}/tokens/{id}
     * 
     * 
     * @param org 
     * @param workspace 
     * @param id 
     * @param requestBody 
     * @return ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun workspaceUpdatePATWithHttpInfo(org: kotlin.String, workspace: kotlin.String, id: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : ApiResponse<kotlin.collections.Map<kotlin.String, kotlin.Any>?> {
        val localVariableConfig = workspaceUpdatePATRequestConfig(org = org, workspace = workspace, id = id, requestBody = requestBody)

        return request<kotlin.collections.Map<kotlin.String, kotlin.Any>, kotlin.collections.Map<kotlin.String, kotlin.Any>>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation workspaceUpdatePAT
     *
     * @param org 
     * @param workspace 
     * @param id 
     * @param requestBody 
     * @return RequestConfig
     */
    fun workspaceUpdatePATRequestConfig(org: kotlin.String, workspace: kotlin.String, id: kotlin.String, requestBody: kotlin.collections.Map<kotlin.String, kotlin.Any>) : RequestConfig<kotlin.collections.Map<kotlin.String, kotlin.Any>> {
        val localVariableBody = requestBody
        val localVariableQuery: MultiValueMap = mutableMapOf()
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Content-Type"] = "application/json"
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.PATCH,
            path = "/v1/organizations/{org}/workspaces/{workspace}/tokens/{id}".replace("{"+"org"+"}", encodeURIComponent(org.toString())).replace("{"+"workspace"+"}", encodeURIComponent(workspace.toString())).replace("{"+"id"+"}", encodeURIComponent(id.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
